src/circuit/circuit_frame.rs
src/proof/nova.rs

This PR fixes a bug which led to unsatisfied constraint systems. When we added provable support for `Terminal` continuations reducing to an identity transformation of all inputs, the circuit wasn't updated accordingly. This fixes that.

Fix terminal continuation circuit bug.

---

README.md

Replacing GitHub CI status badge with CircleCI status badge

Replace ci badge

---

fcomm/src/lib.rs

To make the associated json more human-readable.

Serialize CID fields to strings.

---

Cargo.lock
Cargo.toml
src/circuit/circuit_frame.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/pointer.rs

This PR depends on https://github.com/filecoin-project/neptune/pull/148 and should wait for a next `neptune` release.
It takes advantage of the optimized poseidon circuit and provides 21% constraint reduction immediately.

Use optimized neptune hash circuit.

---

fcomm/src/bin/fcomm.rs
src/circuit/circuit_frame.rs
src/eval.rs
src/proof/nova.rs
src/store.rs

The next tasks were accomplished: 
*  Return error in the following situations (similarly for `cdr`): 
- `(car car)`, since tag is symbol.
- `(car #\a)`, since tag is char. 
- `(car 42)`, since tag is num.
- `(car (lambda (x) x))`, since tag is fun.
* Also, add check for `(car NIL)` is NIL.
* Refactored eval.rs to check programs end with terminal continuation.

Car cdr invalid tag error

---

src/circuit/circuit_frame.rs

As implemented in `apply_continuation()` we optimized construction of pointers in `reduce_cons()`, by using an extra `multicase` gadget to selected the hash pre-image, and then calling `construct()` only once.

Reduce cons optimization

---

README.md
examples/repl.rs
src/field.rs
src/proof/nova.rs
src/repl.rs
tests/lurk-tests.rs

Support multiple fields in REPL, defaulting to the scalar field of Pallas. For now, selection is by env var, but we should probably add a command-line option also.
```
➜  lurk-rs git:(repl-backend) ✗ bin/lurkrs
Compiling lurk v0.1.1 (/Users/clwk/fil/lurk-rs)
Finished release [optimized] target(s) in 4.50s
Running `target/release/examples/repl`
> (- 0 1)
[3 iterations] => 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000000
> 
Exiting...
➜  lurk-rs git:(repl-backend) ✗ LURK_FIELD=PALLAS bin/lurkrs
Finished release [optimized] target(s) in 0.12s
Running `target/release/examples/repl`
> (- 0 1)
[3 iterations] => 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000000
> 
Exiting...
➜  lurk-rs git:(repl-backend) ✗ …
```

Support alternate fields in REPL.

---

src/repl.rs

This PR fixes the `!(:assert-eq …)` REPL command to perform a proper `Ptr` equality check and not just check for Rust data-structure equality.
Before:
```
!(:assert-eq (comm 0x185e06ceae235e35b0b54a0032c97c22cde058f810583b4fb8aedf2f1c7aa7f2) (commit 123))
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `Ptr(Comm, RawPtr(-1, PhantomData))`,
right: `Ptr(Comm, RawPtr(0, PhantomData))`', /Users/clwk/fil/lurk-rs/src/repl.rs:292:33
```
After:
```
!(:assert-eq (comm 0x185e06ceae235e35b0b54a0032c97c22cde058f810583b4fb8aedf2f1c7aa7f2) (commit 123))
```

Use store.ptr_eq in !(:assert-eq ...).

---

spec/reduction-notes.md

Clarify that terminating evaluation results being a fixed-point of reduction depends on considering the continuation (and lexical environment) as part of the reduction step's I/O.
That is, it's not the case that repeated *expression evaluation* will result in unchanged subsequent results.
A clarifying example:
```
> (+ 1 1)
[3 iterations] => 2
> 2
[1 iterations] => 2
> ;; 2 is self-evaluating.
> '(+ 1 1)
[1 iterations] => (+ 1 1)
> (+ 1 1)
[3 iterations] => 2
> ;; (+ 1 1) is not self-evaluating.
```

Clarify reduction explanation.

---

src/circuit/circuit_frame.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/pointer.rs
src/eval.rs
src/proof/nova.rs
src/store.rs

This PR incorporates https://github.com/lurk-lang/lurk-lib/pull/26 and makes the `lurk_tests` pass after doing so. It also adds equivalent unit tests for eval and circuit.

Update for Str behavior change.

---

src/circuit/gadgets/data.rs
src/circuit/gadgets/pointer.rs

This PR creates a single function (`hash_poseidon`) through which all calls creating hashes in the circuit should pass. This will help with instrumentation so we can optimize the circuit to reduce/minimize hashing.

Wrap poseidon_hash to facilitate instrumentation.

---

src/eval.rs
src/parser.rs
src/writer.rs

Closes #125, closes #136.
Symbols containing any character ~(except '|')~ can now be used by quoting with '|'. ~The lack of internal quoting is a bug equivalent to the same current lack for strings (see #136).~
In the future, we can consider making the reader directly aware of more symbol characters, allowing them in symbol names, without quoting. For now, explicit quoting should work.
Tests include greek and symbol examples. The following example works in the REPL, though I avoided emoji in the source since it wreaked havoc with my editor.
```
> (let ((|🐊| 9)
(|🐉| (lambda (|🍓|) (* |🍓| |🍓|))))
(|🐉| |🐊|))
[13 iterations] => 81
```

Support quoted symbols.

---

src/repl.rs

When loading a Lurk file in the REPL (with `:load`), only the first expression was previously processed. This PR extends this behavior to process expressions sequentially. In this context, 'process' means the expression is evaluated, and the REPL's env is replaced with the result.
Idiomatically, file loading is used to define library code, by returning `current-env` from within a lexical scope which binds some variables (often to functions).
Previously, all such definitions had to be created within a single expression. However, it is convenient when writing library code, to write independent top-level definitions.
The behavior introduced in this PR allows that. For example, consider loading a Lurk file containing the following code:
```
(let ((square (lambda (x) (* x x))))
(current-env)) …
```

Processs multiple expressions when loading from REPL.

---

src/eval.rs
src/num.rs

#133 incorrectly handled the case where both args to a relational operator are negative. This PR tests and fixes that.

Correctly handle < when both args are negative.

---

src/circuit/circuit_frame.rs
src/circuit/gadgets/data.rs
src/eval.rs
src/proof/mod.rs
src/proof/nova.rs
src/scalar_store.rs
src/store.rs
src/writer.rs

This PR removes the `Relop` and `Relop2` continuation times. It no longer makes sense to separate these from `Binop` and `Binop2`. Removing them and moving `eq` and `=` to `Binop` and `Binop2` allows us to remove a lot of nearly-duplicated code and also removes some constraints.

Remove Relop and Relop2.

---

src/circuit/circuit_frame.rs
src/eval.rs
src/proof/nova.rs
src/store.rs
src/writer.rs

This PR fixes a bug I discovered while writing some elaborate examples, then minimized and fixed. Previously, zero-arg functions were being called with a `Call0` continuation which did not save and restore the lexical environment. For more detail, see the test — which also includes a case which always works and helps clarify exactly what was failing.
I've fixed this behavior by extending `Call0` to include the saved env and modified the handling in `eval.rs`. The circuit still needs to be adjusted for these changes, and @emmorais will take over from here.

Test nested let regression.

---

Cargo.lock
Cargo.toml
src/eval.rs
src/parser.rs
src/repl.rs
src/writer.rs

This PR adds support for fractional syntax when parsing Nums. When this syntax is used, the resulting num is calculated, at read-time, by performing a field-element division. This means that for arithmetic and algebraic purposes, the resulting field elements appear to behave like the corresponding rationals. However, note carefully, that this similarity does not extend to relational comparisons. For details and more examples, see the tests in `eval.rs`.

Support reading field elements (Nums) with fractional syntax.

---

README.md

The README wrongly labeled all field options as default. This PR fixes that.

Fix README text.

---

src/eval.rs
src/store.rs

This PR adds support for eval, which is quite trivial. We just add a new `Unop` (`Op1::Eval`), which returns its evaluated argument as the next expression to be evaluated (using the`Unop`'s saved continuation).
TODO: Circuit (as separate PR). CC: @emmorais

Support EVAL.

---

src/circuit/circuit_frame.rs

The same car_cdr was used twice. This PR refactors it to optimize the circuit.

Optimize the circuit

---

fcomm/src/lib.rs
src/error.rs
src/parser.rs
src/repl.rs
src/store.rs

The parser returns `None` when it encounters bad input, this doesn't tell the user (eg at the repl) what is wrong. Instead of returning `Option`, let's return a `Result` with meaningful error messages that we can bubble up. Also introduce a new error type to carry these errors.
This PR also fixes #146 and addresses some instances where inner code panics (but probably not all).

Improve parser error handling, fix repl panics

---

src/eval.rs
src/field.rs
src/lib.rs
src/num.rs
src/parser.rs
src/scalar_store.rs
src/store.rs
src/uint.rs
src/writer.rs

This PR adds support for fixed-width (64-bit) unsigned integers. With an eye to potential future work, it defines a general `UInt` enum, of which `UInt::U64` is the only initial variant.
Arithmetic behaves as though `mod 2^64`. Division is 'integer division'.
Literal `U64`s are denoted with a suffix, either `u64` or `U64` directly following a valid number. It is a reader/parser error to specify a `U64` from a number greater than the maximum `U64`.
The `num` operator coerces `U64` to `Num`, with no loss of precision.
The `u64` operator coerces `Num` to `U64`, preserving only the least-significant 8 bytes.
Arithmetic operations that mix `U64` and `Num` yield `Num`s and are performed by first coercing the `U64` to `Num`.
The `u64` suffix cannot be combined with negative or fractional …

Support U64

---

src/eval.rs
src/parser.rs
src/store.rs

Now that we have `U64`, supporting mod is easy. The implementation assumes that both args are `U64` and returns a `U64`.
This PR also adds some missing tests showing that it is an error to apply a numeric operator to a non-numeric argument. These should be ported to the circuit, since explicit proof of error conditions needs to be tested.

Support modulo operator for u64.

---

src/eval.rs
src/store.rs

#160 only supported one-arg EVAL. This PR adds support for the optional second argument. If supplied, the second argument is used as the env when evaluating. Note that the second argument is evaluated as usual before use.

Support optional second-arg (env) to EVAL.

---

src/circuit/circuit_frame.rs
src/circuit/gadgets/case.rs

For all multi_case gadgets, the size of defaults must be equal to the number of cases. We added an `assert_eq!` to guarantee this condition. 
It allowed us to find 2 places where this condition didn't hold. This PR fixes this problem.

Fix defaults length

---

src/circuit/circuit_frame.rs
src/circuit/gadgets/case.rs

There were some allocated constants (zero and one) used in `Case` and `MultiCase` gadgets but without actually constraining the allocations to equal the required values. This PR fixes that by using the globally allocated constants for this purpose. This avoids adding new constraints, and in fact removes some now-redundant allocations.

Ensure soundness of constant allocations by using GlobalAllocations.

---

src/eval.rs
src/parser.rs
src/proof/groth16.rs
src/proof/nova.rs
src/repl.rs
src/store.rs

There was a bug in the tests, such that an empty store was being used to check output values. On top of that, equality tests were returning `true` when neither value was in the store. So the equality checks in those proof tests (in `nova.rs`) were always succeeding.
This PR fixes the tests and the underlying equality test by:
- Making `ptr_eq()` return a `Result`, with an error if either `Ptr` is missing from the store.
- Checking tag equality in `ptr_eq()`.
- *Not* mistakenly creating and using a new empty store (!?) in the nova tests.
- Using `ptr_eq` (rather than Rust equality checking) in the Groth16 tests.
It also adds a test which would have failed with the previous code. Specifically, we now check that a test which passes the wrong expected value to the helper function indeed fails …

Improve equality testing.

---

Cargo.lock
src/parser.rs
src/repl.rs
src/writer.rs

When #180 introduced self-evaluating keyword symbols, the `:load <filename>` 'command' behavior in the REPL was broken.
This PR replaces that functionality by supporting the `!(:load <filename>)` syntax. It also makes all the other `!(:command …)` forms available at the REPL (not just when loading or running files).
This is a divergence from [Lisp Lurk](https://github.com/lurk-lang/lurk)'s REPL, which will probably not be updated to match the new (preferred) behavior.

Support ! commands in REPL.

---

src/parser.rs

There's several possible conventions for predicate names, and appending a `?` is one of them, which needs this change to allow.

Allow '?' in symbols to enable predicate names like 'odd?'

---

src/repl.rs

Also make variable names more specific, to avoid further confusion.
The problem was detected in the CI tests for another PR, see #194. 
We get
```
Running from lurk-lib/example/test.lurk.
Read from lurk-lib/example/test.lurk: !(:load "lib.lurk")
!(:assert-eq (square 8) 64)
!(:assert-eq (square 9) 81)
!(:assert (eq (square 10) 100))
Loading from lurk-lib/example/test.lurk/lib.lurk.
thread 'lurk_tests' panicked at 'called `Result::unwrap()` on an `Err` value: Not a directory (os error 20)
```
Note the `Loading from lurk-lib/example/test.lurk/lib.lurk` - we forgot to drop the filename part of the path before continuing to handle forms. `test.lurk` is the name of the current file, and `lib.lurk` is the one being loaded.
I am not sure though, why CI tests did not start …

Fix call to handle_form to pass dir and not file path

---

src/repl.rs

When loading a file, if there's a parse error, return it instead of returning Ok. The exception is `ParserError::NoInput` which is what we expect at EOF. If we get that, just return `Ok`.
To reproduce:
* put some bad input in a file called `foo.lurk` (I just put one double-quote character in it, so parsing will fail).
* `cargo run foo.lurk`
You'll get empty output and lurkrs returns 0 exit code as if the run was successful. I stumbled upon this when I had a typo in one of my files, it looked like it executed but it actually had just swallowed the error.

Don't swallow parsing errors when reading from file

---

src/repl.rs

When running from a file, it's a non-interactive mode, so no need to print the REPL welcome message (there is no REPL).
```
~/workspace/lurk-rs $ cargo run ../lurk-lib/foo.lurk
Finished dev [unoptimized + debuginfo] target(s) in 0.84s
Running `target/debug/lurkrs ../lurk-lib/foo.lurk`
Running from ../lurk-lib/foo.lurk.
Read from ../lurk-lib/foo.lurk: (let ((foo (lambda () "foo")))
(current-env))
[3 iterations] => ((FOO . <FUNCTION () "foo">))
~/workspace/lurk-rs $ cargo run
Finished dev [unoptimized + debuginfo] target(s) in 0.12s
Running `target/debug/lurkrs`
> "foo"
[1 iterations] => "foo"
> Exiting...
~/workspace/lurk-rs $ 
```

Only print the welcome message when running actual REPL

---

fcomm/tests/proof_tests.rs
src/circuit/circuit_frame.rs
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/hashes.rs
src/circuit/gadgets/macros.rs
src/circuit/gadgets/mod.rs
src/circuit/gadgets/pointer.rs
src/eval.rs
src/hash_witness.rs
src/lib.rs
src/proof/nova.rs
src/store.rs

This PR optimizes the hashes used to represent Cons in the circuit and also likely fixes soundness problems. The latter probably existed because the decision as to whether or not a particular Cons is 'real' (and therefore constrained to be equal to an expected value) depended on whether it was present in the store, rather than being deterministically calculated from the inputs.
NOTE: this problem likely still affects other parts of the circuit where hashes are similar constructed. This will be addressed in subsequent work extending the method used here to include them. The result should be that all hashing gadgets/functions should take an explicit boolean argument signaling whether the hash is a 'dummy' or not, and there should not be allocations without corresponding constraints …

Optimize circuit by minimizing Cons hashes.

---

src/circuit/circuit_frame.rs
src/proof/nova.rs

The type coercion circuit functions were performing unconstrained allocations. Now they just construct a new AllocatedPtr, reusing the value of the input and a globally allocated tag.
I also added more tests of invalid input for the coercion operators.
Importantly, the coercion helpers are not responsible for checking the validity of the input type. Also, when coercing to a char, we don't currently check that it is in range. See FIXME comment. We should either return an explicit error or truncate to u32 range. This needs a new issue.

Ensure type coercions are constrained.

---

fcomm/tests/proof_tests.rs
src/circuit/circuit_frame.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/hashes.rs
src/circuit/gadgets/macros.rs
src/circuit/gadgets/pointer.rs
src/eval.rs
src/hash_witness.rs
src/num.rs
src/proof/nova.rs
src/store.rs

This PR extends the technique introduced in #199 to allocated named continuations. It turns out that only two continuation hashes are required per reduction, so this work reduces the circuit by about another 1,000 constraints.
It has also become clear that the previous approach was also error-prone. The enforced discipline required to pass allocated booleans indicating whether any given hash usage is 'real' or 'dummy' proved valuable. As a result, I ended up discovering a number of soundness problems throughout the circuit. These in turn had sometimes masked correctness issues undetected by tests. That possibility points to a pervasive risk. Future work will address the risk by moving away from an ad-hoc, manual circuit and toward an approach that will be sound by construction.
In the …

More hashing optimizations

---

Cargo.lock
src/circuit/circuit_frame.rs
src/eval.rs

This PR adds constraints on the expression and environment, when the continuation is an error in `reduce_sym`. It also incidentally adds some missing `CIRCUIT: …` documentation comments in `eval.rs`, renames some variables, and slightly modifies a condition to reduce a few constraints. All these changes are in response to comments from @adr1anh.

Constrain expr and env when cont is error.

---

src/eval.rs
src/proof/nova.rs

This aligns the behavior of u64's mod with that of div, see #166 for the original inclusion of mod.
Fixes #197

fix: return an error on a u64 mod-by-zero

---

src/circuit/circuit_frame.rs
src/error.rs
src/eval.rs
src/field.rs
src/hash_witness.rs
src/proof/nova.rs
src/store.rs

Closes #230.
This PR refactors and significantly simplifies the error types. As part of that effort, the `Explicit` error variant becomes `Control::Error` — which makes very clear (as desired) that this is part of the Lurk language's control flow rather than an implementation, runtime, store, etc. error encountered during reduction.

Refactor errors

---

CONTRIBUTING.md

Gets the ball started on the contributing doc. Fixes #226 
This uses Github Markdown [callout syntax](https://github.com/community/community/discussions/16925)

chore: add a CONTRIBUTING draft

---

CODEOWNERS

Closes #234.
This is intended as a minimal starting point, from which we can iterate and potentially add more granular and/or permissive ownership over time.

Add minimal CODEOWNERS file.

---

src/circuit/circuit_frame.rs
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/data.rs
src/eval.rs
src/field.rs
src/proof/nova.rs

Similarly to u64, we implemented coercion to u32, which allows us to have coercion to char. 
We do it by taking the last 4 bytes of the field element. Therefore, we have that for `N = 2^32 + x`, then`(eq (char N) (char x)) => T`. In other words, char coercion is equal to the remainder of division by 2ˆ32.

Implement coercion to u32 (and to char)

---

src/repl.rs

This PR supersedes the placeholder, #217. Now runtime errors during the E(valuation) part of the REPL don't break the L(oop).
Although this does fix #178 in the literal sense, the underlying problem is related to Lurk-level error-handling, so let's not close it with this.

Don't exit REPL on runtime error.

---

Cargo.toml
src/field.rs
src/scalar_store.rs
src/store.rs
src/sym.rs
src/tag.rs
src/uint.rs

This is a follow-up to #229 and hence #240 that leans into the derivability of `Arbitrary`. It derives those implementations of `Arbitrary` that trivially can (i.e. those that do not rely on the `FWrap` newtype, or custom behavior such as that of `ScalarStore`).
The regularity of this derivation ensures that these implementations are more maintainable, as we won't have to update them if one of e.g. the Tag enums change.

feat: derive Arbitrary implementations

---

.circleci/config.yml
.config/nextest.toml
src/sym.rs

This introduces the use of [nextest](https://nexte.st/) in CI. This is expected to bring performance improvements for some jobs, due to a [better parallelization model](https://nexte.st/book/how-it-works.html) - except for the `linux-release` job, which is completely sequential anyway. (Edit: the linux-release job is made non-sequential in this PR. The linux job is a wasm job)
Since [nextest does not support documentation tests](https://github.com/nextest-rs/nextest/issues/16), this introduces a perfunctory doctest ahead of the CI change, and runs a separate `cargo test --doc` task.
The goal of this CI is to introduce feature parity with the existing, and it does not aim to change behavior (yet).

Use nextest in CI

---

src/circuit/circuit_frame.rs
src/eval.rs
src/proof/nova.rs

Make calling functions with malformed bodies an error.

---

src/circuit/circuit_frame.rs
src/proof/nova.rs

Replaces #256.
This PR fixes the problem with #256 noted in the second commit.
I'll also take a cut at using the 'constant symbol' optimization described in the comments. This might require a fair bit of refactoring, though. If it gets to be too much, we can defer or separate into a separate PR.

Optimize def_head_sym.

---

Cargo.lock
src/circuit/circuit_frame.rs
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/macros.rs
src/circuit/gadgets/pointer.rs
src/proof/nova.rs
src/store.rs

This PR eliminates 200 constraints by using constants instead of allocations where possible. This is sometimes cheaper inherently, and sometimes allows us to avoid constraints in the global allocation. It also factors out the work of interning symbol pointers so this happens only once, not while synthesizing the circuit for each frame (but this doesn't change number of constraints, just avoids unnecessary work while proving).

Prefer constants to allocations where possible.

---

.github/workflows/licenses-audits.yml
deny.toml

This uses [cargo-deny](https://github.com/EmbarkStudios/cargo-deny). The configuration is the default template modified to allow:
- BSL-1.0,
- MIT,
- BSD 2.0 and 3.0,
- Unicode-DFS-2016
- Apache 2.0
and to warn on copyleft licenses (e.g im)
This also runs a check against the rust advisory DB, equivalent to cargo-audit.

ci: Adds a cargo-deny config and a CI job running it on PRs

---

src/circuit/gadgets/constraints.rs

note: #259 introduced a function without the test attribute, this fixes it.

fix: convert constraints tests to proptest

---

src/circuit/circuit_frame.rs

This removes a FIXME which was addressed in #245.
Once merged, this will allow checking of the final box in #71.

Remove defunct FIXME.

---

Cargo.toml

This:
- makes running tests go from 2180 to 528s on my machine,
The rest of the dev profile is unchanged:
```
debug = true
debug-assertions = true
overflow-checks = true
panic = 'unwind'
incremental = true
rpath = false
```
See [doc](https://doc.rust-lang.org/cargo/reference/profiles.html#default-profiles)

feat: Introduces a dev profile

---

src/circuit/circuit_frame.rs
src/eval.rs
src/hash_witness.rs
src/store.rs

This PR extends the `NamedConstants` in the `Store` to also hold `Ptr`s — and uses those during evaluation rather than constantly calling `Store::lurk_sym(…)`. These calls made evaluation become horribly slow when hierarchical symbols were introduced, because of a very bad and unperformant initial implementation. That performance should be improved when some of the LDON work lands. However, even if symbol interning becomes 'cheap', it's still an expensive operation to perform many times per reduction. This PR therefore fixes the root performance problem, which predated the symbol change.
See benchmark results below for an 11x speedup (-91% time).
```
Running benches/eval.rs (target/release/deps/eval-60f9add2215a78cb)
WARNING: HTML report generation will become a non-default optional …
```

Optimize eval syms

---

Cargo.lock
Cargo.toml
clutch/Cargo.toml
clutch/README.md
clutch/bin/clutch
clutch/src/main.rs
src/main.rs
src/repl.rs
tests/lurk-tests.rs

This PR ~adds REPL env state manipulation commands. It also~ adds the clutch crate with minimal support for proving and verifying from the REPL. The immediate purpose of clutch is to support near-term demos that will benefit from a more featurefull REPL. Longer term, it will be used to integrate functional commitments, proofs, and meta-Lurk development without committing the core language to experimental prototypes. Some features are expected to migrate back into the `lurk` or `fcomm` crates once well understood.

Add clutch crate with enhanced REPL

---

fcomm/src/lib.rs

This PR adds a missing verification check in the case (never exercised by fcomm currently) that an iteration count is supplied. For reasons explained in the comment, this is somewhat complicated and depends on eventual changes to Nova and more sophistication from Lurk itself. Meanwhile, the primary value is an incremental improvement to correctness and a comment better explaining the situation.

Add placeholder to verify claim iterations.

---

clutch/src/main.rs
fcomm/src/bin/fcomm.rs
fcomm/src/lib.rs
fcomm/tests/proof_tests.rs
src/error.rs
src/repl.rs
src/store.rs

This PR add support for `!(:commit …)` and `!(:open …)` commands from the clutch REPL. It incidentally also renames the function map and related types/directories in fcomm to be more general, since there was not actually anything function-specific (apart from the names) about them. NOTE: this does mean that any local committed functions will no longer be findable unless migrated manually.
Two-arg `!(:commit …)` adds a secret, but somewhat counter-intuitively reverses the args from what `.lurk.hide` does. Maybe we should add `!(:hide …)`. Likewise, a one-arg commit command that produces a random secret (like in fcomm). We could also just mirror fcomm, with no default 0 secret… and with the one-arg version giving the random secret.
See example below. The REPL is closed and reopened between …

General commitments

---

fcomm/examples/chained-function.json
fcomm/examples/num-list-function.json

This is cleanup to make the example json consistent with the struct changes in #284.

Rename fun keys to expr in fcomm example json.

---

.github/workflows/benchmark.yml
.github/workflows/docs.yml

This introduces two jobs using [GitHub Actions](https://github.com/features/actions):
- the docs job, which publishes the Rustdoc of our crate on the go-pages branch to be published with [Github pages](https://pages.github.com/). [Example of a CI run on my fork](https://www.garillot.net/lurk-rs/docs/). The job is triggered on master pushes or manually. [^1]
- the benchmarks job, which runs the criterion bench on a GitHub machine (yes, this sucks: I plan to make better with self-hosted runners), and maintains a historical log of those benchmarks. [Example of a CI run on my fork](https://www.garillot.net/lurk-rs/benchmarks/criterion/reports/). The job is triggered by GH releases or manually. [^2]
[^1]: expected URL of the eventual output (once merged and triggered) …

CI: generate rustdoc + benches

---

.circleci/config.yml

The current `medium` class is [now deprecated](https://discuss.circleci.com/t/macos-resource-deprecation-update/46891), so this PR updates to the recommended Gen2 replacement. Incidentally, this reduces Mac CI time by ~40% and brings the total time down to around 16 minutes.

CI: Update Mac resource class to Gen2

---

Cargo.toml
src/num.rs

- fixes one bug in a test,
- codegen-units=1, introduced in #273, is rather extreme and cuts parallelism in compilation without adding much speed (ant least on my machines)

[test] fix a Prop unit test

---

.circleci/config.yml

Since #280, CI generates pushes to gh-pages, which does not have a CircleCI config.
The following should make CircleCI not trigger, cleaning up the build log.

chore: don't trigger CI on gh-pages

---

tests/lurk-tests.rs

If the lurk-lib submodule hasn't been initialized properly, the `lurk_tests` test will fail in a way that's non-immediate to diagnose.
This will make what's going on obvious.

fix: print an error message if the lurk-lib submodule hasn't been initialized

---

Cargo.lock
clutch/Cargo.toml
clutch/demo/simple.lurk
clutch/src/lib.rs
clutch/src/main.rs
fcomm/src/lib.rs
src/main.rs
src/repl.rs
tests/lurk-tests.rs

This PR adds support for a candy-like demo mode to clutch. If a `--demo` argument is provided, it names a file used to get a list of REPL inputs. Inputs in the provided script are separated by blank lines. If provided, these inputs will be sequentially supplied to the REPL when an empty line is received. In concert with this fakery, the next demo line to be supplied will be appended to the prompt. The net effect is that repeatedly pressing return (entering blank lines) will walk through the supplied demo script.
Here's the resulting output, using the simple demo script provided in this PR:
```
➜  clutch git:(clutch-demo) ✗ bin/clutch --demo demo/simple.lurk        
Finished release [optimized] target(s) in 0.13s
Running `/Users/clwk/fil/lurk-rs/target/release/clutch --demo …
```

Add demo support and simple demo to clutch.

---

clutch/demo/alpha.lurk
clutch/src/lib.rs
src/circuit/gadgets/data.rs
src/package.rs
src/proof/nova.rs
src/store.rs

This PR makes a few fixes and optimizations discovered while working on the clutch demo.
- Handle interning keywords.
- Avoid interning symbols for every circuit and instead use the `NamedConstant`s.
- Revert circuit tests to check multiple `chunk_frame_count`s.
UPDATE: More optimizations/fixes including a very significant one:
- Handle and edge case in symbol name abbreviation.
- Return cached ScalarPtrs when possible (in (`get_`)`expr_hash()`. This is the big one.
In the demo work motivating these changes, a somewhat complex commitment became stalled out indefinitely at high CPU usage but now completes instantly. I ~will push~ pushed that WIP demo code to this PR also for reference. You can run it with `bin/clutch --demo demo/alpha.lurk` (from `clutch` directory). Just keep hitting …

Fix clutch commitments and some optimizations.

---

src/store.rs

This:
- removes cloning the external symbols `HashSet` on each symbol internalization from the store (this could probably also be removed from the repl),
- adds a few const functions where possible,
- and a few minor cleanups:
```
go_base_10_16_bls12     time:   [3.7405 ms 3.7457 ms 3.7512 ms]
change: [-27.969% -27.813% -27.653%] (p = 0.00 < 0.05)
Found 4 outliers among 100 measurements (4.00%)
4 (4.00%) high mild
go_base_10_160_bls12    time:   [35.656 ms 35.686 ms 35.717 ms]
change: [-28.890% -28.219% -27.799%] (p = 0.00 < 0.05)
Found 7 outliers among 100 measurements (7.00%)
3 (3.00%) low mild
3 (3.00%) high mild
1 (1.00%) high severe
go_base_10_16_pasta_pallas
time:   [3.8389 ms 3.8437 ms 3.8493 ms]
change: [-28.424% -28.246% …
```

Slight store performance improvements (low-hanging fruits)

---

clutch/src/lib.rs
fcomm/src/lib.rs
src/circuit/circuit_frame.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/hashes.rs
src/circuit/gadgets/pointer.rs
src/circuit/mod.rs
src/eval.rs
src/light_data/light_store.rs
src/proof/nova.rs
src/scalar_store.rs
src/store.rs
src/tag.rs
src/writer.rs

This is the non-controversial fragment of #307, which does not change the byte-level representation of `Scalar(Cont)Ptr` tags. This just saves a bit of code (but brings no meaningful performance change).
This simply refactors the definition of `Scalar(Cont)Ptr` to carry in tag position the type they are meant to represent, and adjusts the definitions in function. The implementation of those definitions is shared in a generic type `SPtr`, of which `ScalarContPtr` and `ScalarPtr` are just particular instantiations.
The `Tag` trait appears in `scalar.rs` to constrain the acceptable tags for a `SPtr`, but the `ScalarPointer` trait becomes obsolete and is replaced in this implementation, which means the total number of traits in the repo is kept constant.
Note: the commits each compile and …

Refactor Scalar(Cont)Ptr

---

src/field.rs
src/scalar_store.rs
src/store.rs
src/tag.rs

Fixes #307.
```
go_base_10_16_bls12     time:   [3.1047 ms 3.1121 ms 3.1195 ms]
change: [-19.706% -19.469% -19.215%] (p = 0.00 < 0.05)
go_base_10_160_bls12    time:   [29.734 ms 29.819 ms 29.906 ms]
change: [-19.368% -19.070% -18.767%] (p = 0.00 < 0.05)
go_base_10_16_pasta_pallas
time:   [3.1728 ms 3.1768 ms 3.1808 ms]
change: [-18.493% -18.204% -17.952%] (p = 0.00 < 0.05)
go_base_10_160_pasta_pallas
time:   [30.472 ms 30.538 ms 30.610 ms]
change: [-18.865% -18.513% -18.159%] (p = 0.00 < 0.05)
Found 3 outliers among 100 measurements (3.00%)
2 (2.00%) high mild
1 (1.00%) high severe
```

Speed up tag's to_field_bytes

---

Cargo.lock
Cargo.toml
src/repl.rs

- the update of neptune allows us to upgrade to @emmorais fixes re: neptune padding,
- the rustyline fork seems no longer needed to compile to wasm

Maintenance PR: update rustyline, neptune

---

.github/CODEOWNERS

- Implement GitHub action to validate CODEOWNERS file
- Add @huitseeker as a secondary owner in .github/CODEOWNERS
- Exclude @huitseeker from selected directories in .github/CODEOWNERS

ci: Add huitseeker as secondary owner and update CODEOWNERS exclusion.

---

.github/CODEOWNERS

- Add new global owner @lurk-lab/noncircuit
- Modify global owners list to include @porcuquine and @huitseeker
- Include @emmorais only for the path /src/circuit/**

chore: Add and modify GitHub CODEOWNERS global owners list.

---

.circleci/config.yml
Cargo.lock
Cargo.toml
fcomm/Cargo.toml
fcomm/tests/proof_tests.rs
rust-toolchain.toml
src/field.rs
src/num.rs
src/store.rs

- fixes documentation and usage of `is_zero_vartime()` in `num.rs`
- improves documentation in `field.rs`
- the lack of checks, notably overflow checks, due to our running in `--release` mode, hides overflow behavior. #273 allows us to run tests efficiently without release mode (at 3% slowdown), so this:
- removes `--release` from CI,
- includes a custom profile and additional commands for running the circuit tests w/o debug assertions
- updates the toolchain to 1.68.2 and correspondingly fixes some clippy warnings,
- removes the `tempdir` dependency from the project, which was unmaintained and affected by a RUSTSEC.

Pre-release fixes

---

clutch/src/lib.rs
src/repl.rs
tests/lurk-tests.rs

This PR dramatically simplifies handling of REPL commands generally:
- updates to use latest `lurk-lib`, which as of [this PR (#33)](https://github.com/lurk-lab/lurk-lib/pull/33), no longer depends on the legacy loading behavior for updating the env to allow library definition
- remove special handling of expression evaluation results when loading files (previously used to set repl state's env)
- remove `!(:run …)` completely, since `!(:load …)` no longer has special behavior
- remove legacy 'command' handling completely
Now `(:load …)` just loads and evaluates forms sequentially, handling meta if present.
There used to be special handling to suppress iteration count when loading, but that was lost. We can clean up some ergonomics over time, but this change provides much-needed …

Simplify REPL commands

---

Cargo.lock
Cargo.toml
src/repl.rs

Follow-up of #316 and #321: we use a fork of rustyline for compatibility reasons and would like to replace it with conditional compilation.

Add `rustyline/with-file-history` feature for non-Wasm targets

---

clutch/src/lib.rs
fcomm/src/lib.rs
src/circuit/circuit_frame.rs
src/circuit/gadgets/case.rs
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/hashes.rs
src/circuit/gadgets/mod.rs
src/circuit/gadgets/pointer.rs
src/lib.rs
src/light_data/light_store.rs
src/proof/groth16.rs
src/proof/mod.rs
src/proof/nova.rs
src/repl.rs
src/store.rs

- The discipline of importing module doc from the readme is tooling-assisted now,
- lint for ineffective visibility (`#[warn(unreachable_pub)]`), and fix the resulting errors,
- document the proof module,
- other minor changes (e.g. visible lifetimes required in Rust ed. 2021)

Lint module doc & a few other things

---

.circleci/config.yml
clutch/src/lib.rs
fcomm/src/bin/fcomm.rs
fcomm/src/lib.rs
src/repl.rs

This PR increases the number of clutch proofs that can be successfully proved. Because `fcomm` assumes the claims it receives represent their input as strings, it can't handle types that don't (currently) have a readable representation. To fix that, we add support for claims that identify their input and output expr and env by Ptr rather than string. We add special handling for the simple supported cases of continuations, since those are still currently not expressions and therefore would need significant extra work throughout the code base to support uniformly.
The common case this fixes is proving evaluation of an expression that makes use of a function defined in the repl state's env. Because such a function is a *literal* function at this point (rather than a lambda expression that …

Make more clutch proofs work.

---

.circleci/config.yml
clutch/demo/bank.lurk
clutch/demo/chained-functional-commitment.lurk
clutch/demo/functional-commitment.lurk
clutch/demo/simple.lurk
clutch/demo/vdf.lurk
clutch/src/lib.rs
src/repl.rs

UPDATE: This PR failed to merge as expected, but I've updated lurk-lib anyway; and pushed the next set of changes which *disallow* keyword meta commands. There's no reason we need to checkpoint through the rhetorical state of deprecating but allowing the keywords now that we've also merged the PR to update lurk-lib.
---
This PR is a small incremental change, making the 'meta' command syntax from the REPL (lurkrs and clutch) more permissive. Specifically, it allows using non-keyword (no colon) symbols to name commands. Eventually, we will make the non-keyword form mandatory. (The goal is that eventually, meta-lurk is semantically just 'lurk', even though some capabilities cannot yet be included in proofs.)
In order to ease the transition, this PR allows both syntaxes to co-exist. However, …

Don't require keywords for meta commands.

---

README.md
flake.nix

This fixes an issue where `blst` wouldn't recognize the `clang` path if installed with Nix, although there is probably a more direct fix.

Add Nix Wasm build & instructions

---

src/eval/reduction.rs

This is a conservative PR that aims at reducing the level of redundancy in eval.rs.
- this has been partially [codemodded](https://gist.github.com/huitseeker/a4a2752055ee747bfd217d21385bd483), in order to minimize any chance of an edit mistake:
- this has ~~very little~~ no impact on benchmarks:
```
go_base_10_16_bls12     time:   [2.2568 ms 2.2587 ms 2.2607 ms]                                 
change: [+0.4310% +0.5543% +0.6692%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 2 outliers among 100 measurements (2.00%)
1 (1.00%) high mild
1 (1.00%) high severe
go_base_10_160_bls12    time:   [21.565 ms 21.589 ms 21.611 ms]                                 
change: [+0.3615% +0.5026% +0.6417%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 8 outliers among 100 measurements …
```

Remove some redundancy in Eval

---

src/error.rs

Getting rid of impl From<NovaError> in favour of adding #from the corresponding data constructor

Fixing (#339)

---

src/circuit/circuit_frame.rs
src/coprocessor.rs
src/eval/reduction.rs
src/eval/tests/mod.rs
src/proof/nova.rs

The initial implementation wrongly failed to apply the continuation to coprocessor results. The example circuit was also implemented on wrapper enum, rather than the Coprocessor itself. This fixes those issues.

Coprocessor results should be applied to continuation.

---

Cargo.lock
Cargo.toml
clutch/Cargo.toml
clutch/src/lib.rs
examples/sha256.rs
fcomm/src/bin/fcomm.rs
src/circuit/circuit_frame.rs
src/coprocessor.rs
src/eval/lang.rs
src/eval/reduction.rs
src/eval/tests/mod.rs
src/proof/groth16.rs
src/proof/nova.rs
src/public_parameters/error.rs
src/public_parameters/file_map.rs
src/public_parameters/mod.rs
src/public_parameters/registry.rs
src/repl.rs

- adds a Registry for Lang and PublicParams, that is generic in its Coproc parameter,
- makes a singleton instance for it,
- threads the disk-cache probing logic through the Registry,
- Changes static references to the Lang into an Arc,
- corrects tests, warnings and lints..

refactor: add a generic static registry for Langs & PublicParams

---

Cargo.lock
Cargo.toml
clutch/Cargo.toml
clutch/src/lib.rs
examples/sha256.rs
fcomm/src/bin/fcomm.rs
fcomm/tests/proof_tests.rs
lurk-macros/src/lib.rs
src/circuit/circuit_frame.rs
src/circuit/gadgets/mod.rs
src/circuit/mod.rs
src/coprocessor.rs
src/eval/lang.rs
src/eval/tests/mod.rs
src/lib.rs
src/proof/groth16.rs
src/proof/nova.rs
src/public_parameters/error.rs
src/public_parameters/file_map.rs
src/public_parameters/mod.rs
src/public_parameters/registry.rs
src/repl.rs

The main purpose of this PR is to include a benchmark that matches those in the https://github.com/celer-network/zk-benchmark repository.
To run the benchmark run `cargo run --example sha256 1 f5a5fd42d16a20302798ef6ed309979b43003d2320d9f0e8ea9831a92759fb4b false` in the terminal.
The expected output is `T` when the input hex number equals the expected hash, together with timing information for each step of the proof generation and verification.
To achieve the above goal a number of changes in the larger repository are made:
* Define a SHA256 coprocessor using the bellperson SHA256 circuit.
* Fix a bug with coprocessors with arity 0 not evaluating correctly.
* Change the expected reduction count steps for associated tests.
* Change the visibility of some modules so they can be used in an …

Add SHA256 benchmark

---

Cargo.lock
Cargo.toml
src/public_parameters/mod.rs

- Introduce `bincode` dependency to replace `serde_json` in serialization and deserialization
- Improve error message for cache deserialization issues in `public_parameters` module
Contributes to #387 : reduces the reading time by ~2x (1000s to 500s on my machine), the cache size by ~2x (2.1GB to 1.1GB). Hopefully this is just the start.

chore: Optimize public parameter serialization with bincode

---

examples/sha256.rs

If you thought the sha256 benchmark took 4-5 seconds to prove, I have some 10x good news for you.
```
➜  lurk-rs git:(sha256-release-mode) cargo run --release --example sha256 1 f5a5fd42d16a20302798ef6ed309979b43003d2320d9f0e8ea9831a92759fb4b false
Compiling lurk-macros v0.1.0 (/Users/clwk/fil/lurk-rs/lurk-macros)
Compiling lurk v0.2.0 (/Users/clwk/fil/lurk-rs)
Finished release [optimized] target(s) in 26.44s
Running `target/release/examples/sha256 1 f5a5fd42d16a20302798ef6ed309979b43003d2320d9f0e8ea9831a92759fb4b false`
Setting up public parameters...
Using disk-cached public params for lang -SHA256-HASH-64-ZERO-BYTES
Public parameters took 80.586608292s
Beginning proof step...
T
Proofs took 434.543917ms
Verifying proof...
Verify took 274.103041ms
Congratulations! You proved and verified …
```

Document release mode for sha256 benchmark.

---

examples/sha256.rs
lurk-macros/src/lib.rs
src/circuit/circuit_frame.rs
src/coprocessor/mod.rs
src/eval/lang.rs
src/eval/tests/mod.rs
src/proof/nova.rs

Improves coprocessor ergonomics:
- macro derives `From` impl for wrapping enums.
- various support for more conveniently creating `Lang` with symbol-coproc bindings.
- support for coprocessors that don't (yet or perhaps ever in the case of meta-lurk) have circuit implementations.

Improve coprocessor ergonomics.

---

Cargo.lock
Cargo.toml
clutch/Cargo.toml
fcomm/Cargo.toml
lurk-macros/Cargo.toml
src/circuit/circuit_frame.rs
src/circuit/gadgets/case.rs
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/hashes.rs
src/eval/reduction.rs
src/field.rs
src/light_data/light_store.rs
src/num.rs
src/proof/nova.rs
src/store.rs

- Update dependencies for various crates,
- Refactor `LurkField` trait in `src/field.rs` to use updated definitions,
- Update to Nova 0.20,
- Remove use of `TrivialCompComputationEngine` and change type aliases in `src/proof/nova.rs`

refactor: Update dependencies to ff/group version 0.13

---

src/circuit/circuit_frame.rs
src/circuit/gadgets/constraints.rs
src/lem/constrainer.rs
src/lem/eval.rs
src/lem/store.rs

While reviewing #402, I noticed that the idea for implication constraints there could be propagated more broadly. This represents a low-hanging optimization to existing code, which obtains implication constraints through composition in a way that incurs unnecessary constraints.
This PR
- cleans up some of the linear-combination construction from #402.
- factors all implication-related functions for clarity and to encourage the economical construction.
- removes 61 constraints from the current circuit.
- cuts the constraints in #402's example by more than half (68 -> 29).
Since the LEM approach will lean heavily on implication, it's a good idea to finally ensure our basic construct for implementing it is efficient. That will help us maintain a relatively accurate sense of costs as we …

Cleanup and optimize implication constraints.

---

src/lem/constrainer.rs
src/lem/interpreter.rs
src/lem/mod.rs

- Improve error handling by replacing `map_err` with `with_context`
- Reorder import statements in `interpreter.rs` and `mod.rs`

refactor: Improve error handling using with_context

---

src/lem/mod.rs
src/lib.rs

- Use `trace_macros` feature flag in `src/lib.rs`
- Resolve macro conflicts in `src/lem/mod.rs` by fixing lemop rules
CI is 100% expected to fail with 
```
error[E0554]: `#![feature]` may not be used on the stable release channel
```

fix: Improve macro handling

---

benches/end2end.rs
benches/fibonacci.rs
clutch/src/main.rs
src/field.rs
src/main.rs

This PR attempts to rectify confusion and inaccuracy wreaking havoc in our naming of fields. This is really important for multiple reasons. The worst-case situation is one in which we accidentally instantiate a Lurk language on the wrong field. This would lead to incompatible data and great confusion. The less bad cases involve conceptual incoherence, false labeling, and general mayhem in the vicinity of our efforts to produce an evidently correct code base.
Please see individual commits for details. Problems fixed here:
- In some places, the *wrong scalar field* was being used. I believe this problem was introduced in #239, then either independently 'discovered' or else cargo-culted by reference in new benchmarks.
- In some places, type aliases which do not *obviously* match the intended …

Rectify language fields

---

src/coprocessor/mod.rs
src/coprocessor/trie/mod.rs
src/eval/tests/mod.rs
src/eval/tests/trie.rs
src/hash.rs
src/store.rs

This PR adds a trie coprocessor (no circuit yet) theoretically suitable as a key-value store/map. Apart from the lack of a circuit, this implementation is also incomplete due to limitations in coprocessor support generally. One purpose of this work is to uncover such issues.
- The type (tag) of keys is currently ignored. Future work should require that keys all have the same type.
- Arity of the hash used must be a power of two. In practice, this should be 8 for efficiency.
- The value/hash of a key is converted into a bit path and chunked. For example, an 8-ary trie uses paths of 3 bits at a time.
- Values stored are assumed to be commitments. A value of `0` (for which we know no preimage) is used to represent a missing key.
In order for previously-built tries to be readable, hash …

Add trie coprocessor.

---

.gitignore
benches/end2end.rs
benches/public_params.rs

- Explain steps to run and find benchmark results.
- Add `flamegraph` config to `public_params_benchmarks`.

Chore: Add Comments Explaining `criterion/flamegraph` Usage in Benchmarks

---

.cargo/config
.circleci/config.yml
.github/workflows/rust.yml

- Implement a new Rust workflow for GitHub Actions
- Integrate it for pushes and merges to the `master` branch
- Update CircleCI configuration to ignore 'master' branch for select jobs
The CI run on merged commits to master is not merge-blocking (by definition), and kinda redundant with the work of the merge queue. Here we make sure this is off our CircleCI bill, and get a baseline for how long it takes to run on GH Actions.

ci: Run Github Actions instead of CircleCI for pushes to master

---

.cargo/config
.github/workflows/pr_bench.yml

This enables running the PR benchmarking workflow with a `!benchmark` comment, in order to remove noise during PR development and skip benches for PRs that wouldn't benefit from it, such as CI or documentation.
Also updates the toolchain action to use the new `rust-toolchain` file in #435

Run PR benchmarking workflow manually

---

.github/workflows/rust.yml
src/circuit/gadgets/constraints.rs
src/coprocessor/mod.rs
src/coprocessor/trie/mod.rs
src/eval/mod.rs
src/eval/tests/mod.rs
src/eval/tests/trie.rs
src/light_data/mod.rs
src/proof/nova.rs
src/scalar_store.rs
tests/light-data-store.rs

Some of our tooling respects the rust-toolchain file more, and gave us early warning of the issues this fixes.
I'm still chasing the discrepancy between https://github.com/lurk-lab/lurk-rs/actions/runs/5225265251/jobs/9434513894 (up-to-date) and https://app.circleci.com/pipelines/github/lurk-lab/lurk-rs/2626/workflows/5646178f-7b8c-4c84-a6d1-ae2a4c7dc887/jobs/15605 (not)

refactor: Run clippy at rust 1.70

---

.github/workflows/pr-bench.yml

The current version is getting skipped, and also doesn't have access to `github.base_ref` because it isn't triggered by a `pull_request` event. This should fix both issues.

Fix PR bench branch comparison

---

.github/workflows/rust.yml

- Enable recursive submodule checkout for test, clippy, and rustfmt jobs

ci: make checkouts recursive

---

.clippy.toml
clutch/.clippy.toml
fcomm/.clippy.toml
lurk-macros/.clippy.toml
src/coprocessor/mod.rs
tests/light-data-exprs.rs

- installs a .clippy.toml on the heels of #437,
- uses disallowed-methods lint as suggested in #423

More clippy tuning

---

.github/workflows/pr-bench.yml

Gets the comment's PR branch for comparison, rather than the current behavior of comparing master against itself. Also checks the PR is still open, as per https://github.com/xt0rted/pull-request-comment-branch/issues/213#issuecomment-1014442741

ci: Use correct head ref in benchmark

---

.github/workflows/upstream_update.yml

This adds an hourly job that checks every hour that the dev branch does sit on top of the latest main.
If that is not true, it will open an issue stating that, and assigning it to me. If the issue is open, it will update it with the latest info.
If that is true and an issue for this is still open, it will close the issue in question.

ci: add action for signaling the need for rebases on upstream

---

Cargo.lock
src/proof/nova.rs

This PR (to *dev*) adapts to recent changes in upstream Nova. Of note: https://github.com/microsoft/Nova/pull/163

Adapt to upstream nova

---

Cargo.lock
Cargo.toml
src/proof/nova.rs

Updates to version 0.22
See
- https://github.com/microsoft/Nova/pull/163
This fixes #401.

chore: Update nova, adapt to upstream changes

---

.circleci/config.yml

Based on https://circleci.com/product/features/resource-classes/, we should have access to the `arm.xlarge` and `macos.m1.large.gen1` resources on our current plan. This will improve CI efficiency in the short term as we migrate away from CircleCI.

ci: Upgrade Mac and ARM resource classes

---

Cargo.lock
Cargo.toml
fcomm/Cargo.toml
src/circuit/circuit_frame.rs
src/field.rs
src/proof/groth16.rs

This:
- updates docs,
- renames pairing_lib -> pairing, because some tooling (cargo-outdated) doesn't like this particular alias, and I don't think it matters (unlike nova_snark, which stays aliased to nova).
- fixes a doc warning.
This re-establishes our doc-publishing job (currently [broken](https://github.com/lurk-lab/lurk-rs/actions/runs/5478403052/jobs/9978821036))

[easy] Update dependencies, fix docs

---

.circleci/config.yml

This PR makes the `linux_release` job only run tests marked `#[ignore]`, as it currently duplicates the non-ignored tests run on the `linux` job. We will thus get a nice reduction in total CI time, as the `linux_release` job is the main bottleneck after #493.

ci: Ignore `linux_release` tests covered by `linux` job

---

src/store.rs

Since #364, the store relies on `Rc<Refcell<_>>` to ensure unique access to the store.
This introduces a runtime check that would lead to a panic should some other piece of code retain a reference to the store in a call to `get_expr`. In general, the `Rc<RefCell<_>>` isn't *too* bad, but here it's overkill.
This PR eliminates this unnecessary construct, and re-establishes the use of the borrow checker to ensure static memory safety.

refactor: avoid runtime mutability checks in the store

---

examples/sha256.rs
src/coprocessor/trie/mod.rs
src/eval/lang.rs
src/eval/tests/mod.rs
src/parser/syntax.rs
src/symbol.rs
src/syntax_macros.rs

Converting from string to symbol would require running the parser, then dealing with errors. Instead, the `sym!` macro forces the user to get it right, avoiding potential panics.
Closes #495

Remove conversion from string to symbol

---

Cargo.toml
fcomm/examples/Makefile
fcomm/examples/chained-request.json
fcomm/src/bin/fcomm.rs
fcomm/tests/proof_tests.rs
src/public_parameters/mod.rs

- Implemented the switch from general path read/write methods to JSON specific versions in `fcomm.rs`, impacting `CommittedExpression`, `Commitment`, `Proof`, `Claim` and other structs.
- Extended `FileStore` trait capabilities in `mod.rs` to handle JSON paths, including implementations for `Serialize` types.
- Adjusts `fcomm` test commitment values in function.
Repairs fcomm tests, which were broken in #391 by making them read to/from bincode. Fixes #500

feat: Refactor file handling methods in fcomm to JSON format

---

src/parser/syntax.rs

Implement a specialized 'parse_symbol_limb_raw' function to handle raw symbols
Closes #498
Closes #497

Fix parsing for raw symbols

---

Cargo.lock
Cargo.toml
lurk-macros/Cargo.toml
lurk-macros/src/lib.rs
src/eval/mod.rs
src/symbol.rs
src/uint.rs
src/z_data/z_cont.rs
src/z_data/z_expr.rs
src/z_data/z_ptr.rs
src/z_data/z_store.rs

This implements a `serde_test` macro that can generate round-trip serialization tests pegged on an implementation of `proptest::prelude::Arbitrary`. This macro:
- supports generic arguments passed as attributes,
- supports, optionally, a zdata argument to also generate roundtrips through to_z_data / from_z_data.
=> no more boilerplate tests! (and future tests are easier to define)

Streamline serde and zdata round-trip tests

---

Cargo.lock
Cargo.toml

- Updated the 'sppark' dependency to a specific revision in the project's `Cargo.toml` configuration.
- see https://app.circleci.com/pipelines/github/lurk-lab/lurk-rs/3307/workflows/6d31ca4e-3fa8-49c9-acae-570d38c5e3d0/jobs/19864
- see https://github.com/supranational/sppark/issues/12

chore: Update sppark dependency to a particular version

---

Cargo.lock
Cargo.toml
src/public_parameters/registry.rs

- Upgraded the `anymap` dependency to the latest version.
- Refactored the 'AnyMap' type definition, replacing `anymap::any::Any` with `core::any::Any` in `public_parameters/registry.rs`.
- this will invalidate public params

chore: Update 'anymap' dependency and refactor related usage

---

.github/workflows/upstream_update.yml

This auto-rebases the dev branch in case the rebase is trivial, and keeps the former behavior (opening an issue) in case it is not.

ci: Enhance upstream update workflow with rebase and tests

---

Cargo.lock
Cargo.toml
benches/end2end.rs
benches/fibonacci.rs
deny.toml
examples/sha256.rs
fcomm/src/lib.rs
src/cli/lurk_proof.rs
src/cli/mod.rs
src/cli/paths.rs
src/cli/repl.rs
src/eval/lang.rs
src/field.rs
src/proof/nova.rs
src/public_parameters/registry.rs

This PR implements proving and verification for the `lurk` CLI.
* Only the Pallas field and the Nova backend are supported for now
* I avoided reusing the APIs that were built for `fcomm` and `clutch` on purpose. This avoids conflicts and makes the CLI code more self-contained and easy to change. A future refactor might serve the purpose of unifying the underlying code base so `fcomm`, `clutch` and the CLI can sit on top of the same common code
* I've set the code to get configuration parameters from config file, env vars and CLI args (in that order of precedence, with CLI args having the highest priority)
This PR doesn't implement commitments/openings. We'll leave that for a next unit of improvement.
Closes #366

Prove/verify API

---

src/proof/nova.rs
src/public_parameters/mod.rs
src/public_parameters/registry.rs

Added in #88
@winston-h-zhang very rightly notices they are not needed in https://github.com/lurk-lab/lurk-rs/tree/circom-integration

fix: remove uneeded Serialization bounds on Coprocessors

---

Cargo.lock
Cargo.toml
fcomm/src/lib.rs
src/cli/commitment.rs
src/cli/field_data.rs
src/cli/lurk_proof.rs
src/cli/mod.rs
src/cli/paths.rs
src/cli/repl.rs
src/store.rs
src/z_data/z_ptr.rs

* Persist commitments
* Load persisted commitments
* Content-address proofs to generate stable IDs
* Don't prove cached proofs
* Revamp `FieldData` (credits to @huitseeker)
Closes #529

Implement persistent commitments

---

examples/sha256.rs
src/circuit/circuit_frame.rs
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/mod.rs
src/circuit/gadgets/pointer.rs
src/eval/reduction.rs

This PR changes the semantics of the SHA 256 coprocessor example and closes #475. 
The original benchmark evaluated the expression
```
(emit (eq sha_coprocessor (quote expected_result)))
```
The new example changes the coprocessor semantics to take in the expected result as non-deterministic advice and constrains the output of the SHA gadget. The new evaluated expression is:
```
(sha_coprocessor)
```
This should eliminate the 7x overhead from the original example.

Adjust sha256 example

---

.github/workflows/pr-test.yml

This PR enables tests to run on self-hosted Linux runners with GitHub Actions, which would pave the way to switch from CircleCI in a future PR. Some notes:
- Only Linux x86_64 is currently supported, as ARM/MacOS runners will require additional server setup on e.g. MacStadium or EC2.
- For cheaper tasks like the Wasm and bench builds, I created a `misc` job that runs on the cloud-hosted runners.
- The self-hosted runners are deployed using Docker-compose in https://github.com/lurk-lab/gh-actions-runner/tree/main/test-runner, but will need some scaling and/or hardware tweaks over time. Currently, there are 8 runners with a minimum of 4 vCPUs and 8 GB RAM each.
- Successful run on my fork: https://github.com/samuelburnham/lurk-rs/actions/runs/5616765892

Add self-hosted CI for PR tests

---

src/cli/repl.rs

```lisp
> undefined
[1 iteration] => ERROR!
> 'ERROR!
[1 iteration] => ERROR!
```
The first case is a real error and the second is not. The fact that both have the same response is a bit weird.
This PR makes the REPL's answer distinct for those inputs.
```lisp
> undefined
Evaluation encountered an error after 1 iteration
> 'ERROR!
[1 iteration] => ERROR!
```
This PR also implements other ways to handle and inform errors following a similar and consistent logic

Small REPL improvements

---

.github/dependabot.yml
Cargo.lock
Cargo.toml
clutch/Cargo.toml
fcomm/Cargo.toml
lurk-macros/Cargo.toml

This does a round of `cargo update` then sets up dependabot, using the new grouped update feature to not generate one PR per dep (but rather batch updates):
https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

chore: Setup grouped dependabot config + update dependencies

---

.github/workflows/pr-test.yml
.github/workflows/rust.yml

This speeds up the MSRV check action by a few minutes.
Before: https://github.com/samuelburnham/lurk-rs/actions/runs/5624783183/job/15242302546
After: https://github.com/samuelburnham/lurk-rs/actions/runs/5624854347/job/15242509112

ci: Cache the cargo-msrv install

---

src/cli/commitment.rs
src/cli/lurk_proof.rs
src/cli/repl.rs
src/eval/reduction.rs
src/field.rs
src/store.rs

This PR creates proper proof keys - not IDs (yet) - that should uniquely identify proofs based on the backend, the field, the rc and the claim.

Claim hash is no longer the proof id

---

.github/workflows/pr-test.yml

See doc: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore

ci: make pr-test ignore pushes to the merge queue

---

Cargo.lock
Cargo.toml
lurk-metrics/Cargo.toml
lurk-metrics/src/data.rs
lurk-metrics/src/lib.rs
lurk-metrics/src/recorder.rs
src/cli/repl.rs
src/eval/reduction.rs
src/main.rs

This : 
1. adds a simpl-is{h,stic} lurk-metrics crate that collects metrics in a thread-safe manner and sends them to the logs periodically,
2. instruments `eval/reduction.rs` as a proof-of-concept, to display interesting counts for evaluation steps related to env lookups,
3. equips the CLI with metrics initialization (like logs, metrics are noops without a sink, see (1))
```zsh
huitseeker@lightning.local➜~/tmp/lurk-rs(metrics)» RUST_LOG="lurk::metrics=info" bin/lurk                                                  [19:53:18]
Finished release [optimized] target(s) in 0.12s
Running `target/release/lurk`
> (let ((fib (lambda (target)
(letrec ((next (lambda (a b target)
(if (= 0 target)
a
(next b
(+ a b)
(- target 1))))))
(next 0 1 target)))))
(fib 10))
[381 …
```

PoC integration of Metrics

---

Cargo.lock
Cargo.toml
examples/sha256.rs
fcomm/src/bin/fcomm.rs
fcomm/src/lib.rs
src/cli/lurk_proof.rs
src/cli/mod.rs
src/field.rs
src/proof/nova.rs
src/public_parameters/mod.rs
src/public_parameters/registry.rs
tests/lurk-tests.rs

- makes all of our Nova-related structures generic in the type of the used primary scalar field, provided that field can be attached to a curve cycle with the suitable properties (see `CurveCyleEquipped` trait)
- sets up the curve cycle attachments for the `pallas::Scalar` and `bn256::Scalar` fields,
- allows us to start using the Grumpkin cycle.
- making public parameter caching generic, or supporting SnarkPack (#386, it still depends on Nova through `nova::PublicParams`)
- making `clutch` generic, or supporting SnarkPack (it still depends on Nova through `nova::NovaProver`)
- making `fcomm` generic, or supporting SnarkPack (#281, it still depends on Nova through `nova::NovaProver`)
- making the repl generic (#533, it still depends on Nova through `nova::Proof`)
- Implemented the …

refactor: Nova structs become generic on their field type (+ update Nova)

---

src/cli/mod.rs
tests/lurk-cli-tests.rs
tests/lurk-lib-tests.rs

Solve CLI parse order bug

---

README.md
src/cli/mod.rs
src/cli/repl.rs
src/eval/mod.rs

This PR also brings in other improvements:
* Use more basic building blocks for `Evaluator::eval` in order to avoid unnecessary clones. This speeds up evaluation:
```
eval_benchmark/eval_go_base_bls12/_10_16
time:   [540.20 µs 541.31 µs 542.61 µs]
change: [-13.016% -12.822% -12.564%] (p = 0.00 < 0.05)
eval_benchmark/eval_go_base_pallas/_10_16
time:   [539.73 µs 540.17 µs 540.57 µs]
change: [-14.290% -13.874% -13.618%] (p = 0.00 < 0.05)
eval_benchmark/eval_go_base_bls12/_10_160
time:   [5.1792 ms 5.1861 ms 5.1932 ms]
change: [-13.298% -13.154% -13.015%] (p = 0.00 < 0.05)
eval_benchmark/eval_go_base_pallas/_10_160
time:   [5.1816 ms 5.1878 ms 5.1949 ms]
change: [-13.680% -13.468% -13.298%] (p = 0.00 < 0.05) …
```

Allows proving for incomplete computations

---

.github/CODEOWNERS

- Assigned new directory ownerships: `lurk-benches` for the `/benches/**`, `lurk-cli-tools` for the `/src/cli/**`, `/fcomm/**` and `/clutch/**` directories
This should help us share the review workload better.

chore: Update CODEOWNERS file with new directory ownership

---

Cargo.lock
fcomm/Cargo.toml
fcomm/src/bin/fcomm.rs
fcomm/tests/proof_tests.rs

- Removed `AppSettings` and `AppSettings::DeriveDisplayOrder` from `fcomm.rs`, cleaning up unused imports.
See https://github.com/clap-rs/clap/blob/a3d93f485f0178f13fabedc55664071778d3f1d9/CHANGELOG.md?plain=1#L731
- Upgraded 'clap' package in `Cargo.toml` to align with the workspace version.
- Updated 'clap-verbosity-flag' package from '1.0' to '2.0',

chore: Upgrade clap in fcomm

---

Cargo.lock
Cargo.toml

- Propagate 'portable', 'cuda' and 'opencl' features in 'bellperson' and 'nova'.

Fix feature configurations in Cargo.toml

---

.cargo/config
Cargo.lock
lurk-macros/Cargo.toml
lurk-macros/src/lib.rs
src/cli/repl.rs
src/eval/reduction.rs
src/hash_witness.rs
src/lem/circuit.rs
src/lem/pointers.rs
src/parser/syntax.rs
src/store.rs
src/tag.rs
src/z_data/z_cont.rs

Cleans up some boilerplate related to:
- custom implementations of `TryFrom<foo> for MyEnum` when `MyEnum` is `#[repr(foo)]`
- duplicated match arms (and clippy enforcement so this doesn't happen again).

Remove match & TryFrom boilerplate

---

.circleci/config.yml
.github/workflows/bench_pr_comment.yml
.github/workflows/ci.yml
.github/workflows/ci_ignored.yml
.github/workflows/gpu.yml
.github/workflows/nightly.yml

- Removes `arm64` job on CircleCI as we are already testing on ARM via M1 Mac, and I'm not sure we need first-class support for ARM on Linux.
- Moves `linux_release` CircleCI job to self-hosted GH Actions as `linux_ignored`
- Runs above `linux_ignored` on `merge_group` only, as it is expensive to run and seems wasteful to trigger on every PR commit. This is a speculative change and fine to revert, but it may cause bottlenecks on the self-hosted runners.
- Moves the nightly `linux_exhaustive` CircleCI job to self-hosted GH Actions. The cron job currently runs at midnight UTC time, perhaps it would be better in a timezone like ET?
- Splits CUDA tests into parallel CUDA and OpenCL builds to use scaled GPU runners, and removes the dependency on `CC=gcc-10 CXX=g++-10` due to the new …

ci: Transition to self-hosted runners

---

.github/workflows/ci.yml
.github/workflows/ci_ignored.yml
.gitmodules

Fixes submodule error in https://github.com/lurk-lab/lurk-rs/actions/runs/5856346363/job/15875862609
Also changes the `lurk-lib` git module URL to HTTPS, which is not required by the [checkout action](https://github.com/actions/checkout#usage) but simplifies such checkouts in contexts without an SSH key.

ci: Checkout submodule in `linux_ignored` job

---

.config/nextest.toml

Attempts to fix the sporadic timeout error observed in:
- https://github.com/lurk-lab/lurk-rs/actions/runs/5869723458/job/15915316564
- https://github.com/lurk-lab/lurk-rs/actions/runs/5828440849/job/15806166563
Purely speculative diagnosis: this timeout error could be a hardware resource issue on the self-hosted runners or (much less likely) a bug in Nextest.

ci: Decrease nextest timeout and add retry

---

src/circuit/gadgets/constraints.rs
src/lem/circuit.rs
src/lem/eval.rs

This PR optimizes the match expressions in LEM. Here's a table comparing the costs of the current match vs the optimized one:
```org
|                    | CURRENT | OPTIMIZED |
|--------------------+---------+-----------|
| NO DEFAULT         | 3x + 1  | 2x + 1    |
| DEFAULT            | 3x + 2  | 3x + 2    |
| NO DEFAULT, NESTED | 4x + 1  | 2x + 1    |
| DEFAULT, NESTED    | 4x + 3  | 3x + 2    |
```
where `x` is the number of cases; nested matches are the most common matches.
Suppose we have a match like
```rust
match xs.tag {
Expr::Nil => {
foo
}
Expr::Cons => {
bar
}
Expr::Str => {
baz
}
}
```
Then, this is how we translate to circuits: for each case, we allocate a boolean `b`, then add an `implies_equal` (which costs 1) from `b` to `x.tag == tag` (`x` the variable that is matched, …

LEM match optimization

---

.circleci/config.yml
Cargo.toml
README.md
src/symbol.rs
src/writer.rs

I don't know for how long, but printing keywords has been broken on `master`. Maybe this bug was introduced in the PR that added support for packages.
This PR fixes that issue.

Fix printing for keywords

---

src/cli/repl.rs
src/lem/circuit.rs
src/lem/mod.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/nova_lem.rs
src/public_parameters/disk_cache.rs
src/public_parameters/mem_cache.rs
src/public_parameters/mod.rs

Although this has one compile error still, it gets most of the way to implementing `MultiFrameTrait` for `lem::circuit::MultiFrame`. Thanks to @huitseeker for the public-parameter work.

Multiframe trait wip

---

examples/circom.rs
examples/sha256.rs
src/circuit/circuit_frame.rs
src/cli/mod.rs
src/cli/repl.rs
src/cli/repl_lem.rs
src/lem/circuit.rs
src/lem/mod.rs
src/proof/groth16.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/nova_lem.rs
src/public_parameters/disk_cache.rs
src/public_parameters/mem_cache.rs
src/public_parameters/mod.rs
tests/lurk-lib-tests.rs

This PR attempts to partially address #639 my creating `MultiFrameTrait` and implementing it for `MultiFrame`.
In order to accomplish this without also implementing the LEM equivalent, it comments out inclusion of the duplicated LEM code as necessary.
A logical next step would be an attempt to implement `MultiFrameTrait` for LEM in such a way that the duplication can be reduced or eliminated.

MultiFrameTrait

---

LICENSE-MIT

Uses the same heading and formatting as https://github.com/microsoft/Nova/blob/main/LICENSE and https://github.com/microsoft/vscode/blob/main/LICENSE.txt, which will hopefully enable the GitHub license description to show up at the top of the page.

chore: MIT license formatting

---

src/eval/tests/mod.rs
src/store.rs
src/z_data/z_store.rs
tests/lurk-cli-tests.rs

This is yet another fix found during the implementation of #629.
Hashing a symbol should not do `.rev()` on the path. We should do it from left to right because that's how the `Store` interns symbols.
The reasoning is: symbols in the same package differ on hashing just by the tip of the path (the symbol name).
Note: LEM infra already gets this right as a consequence of how its `Store` does the interning, so no change is needed there.

fix hashing of symbols

---

Cargo.toml
benches/fibonacci.rs
benches/sha256_ivc.rs
examples/sha256_ivc.rs
examples/sha256x.rs

Resolves #632 #485. 
We modify the original `sha256` benchmark to receive `n` arguments, and then incorporate it into a full lurk program to show a proof of concept for IVC with coprocessors. In the given benchmark and example, we can declare a `sha256_ivc_n` coprocessor parameterized by arity `n`.
Running `RUST_LOG=info cargo run --release --example sha256 2`, we execute
```
(letrec ((encode-1 (lambda (term) 
(let ((type (car term))
(value (cdr term)))
(if (eq 'sha256 type)
(eval (cons 'sha256_ivc_2 value))
(if (eq 'lurk type)
(commit value)
(if (eq 'id type)
value))))))
(encode (lambda (input)
(if input
(cons 
(encode-1 (car input))
(encode (cdr input)))))))
(encode '((sha256 . '(0 1)) (lurk . 5) (id . 15))))
```
and get the following output as the final frame 🎉 :
```
INFO  lurk::eval > …
```

IVC Coprocessor Benchmarks

---

src/public_parameters/error.rs
src/public_parameters/mem_cache.rs

Replace `eprintln!` by `info!` in case of error when loading cached public params
Closes #654

Fix UX issue

---

Cargo.toml

- Removed the unnecessary `sppark` crate from the patch section in the project's Cargo.toml file
- Witnesses the release of sppark 0.1.5
Fixes #272

chore: Remove `sppark` crate patch from Cargo.toml

---

src/ptr.rs
src/tag.rs

In order to unify the current and LEM ways of defining the primary circuit and operating on it (so as to further #629), we need to abstract away a type that allows the developer to specify the associated types this circuit construction relies on. We started on this path with #644 and #647.
At a high level, each of the two implementations we have in mind for those traits define a single pointer type, rather than two. It would be ergonomic to have one.
The present PR defines `Ptr` and `ContPtr` as two distinct instantiations of a single pointer type, which is something we've wanted to do for a while already. We just needed an excuse.
- Refactored `Ptr` struct into a generic `GPtr` struct, introducing type parameter `T` and associating it with `Tag` interface.
- Created `Ptr` and `ContPtr` …

refactor: Refactor Ptr struct to generic with type Tag

---

examples/sha256.rs
lurk-macros/src/lib.rs
src/circuit/circuit_frame.rs
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/macros.rs
src/circuit/gadgets/pointer.rs
src/lem/circuit.rs
src/z_data/serde/ser.rs

Some error handling is entirely motivated by calling an infallible function that nonetheless returns `Result<>`: `AllocatedNum::alloc`, when called with an infallible closure. 
This PR materializes this as a draft with an `.expect()`, something that incidentally was already done in functions such as `allocate_unconstrained_bignum` -- and is now normalized throughout the code base. 
We should merge the [sister bellpepper PR](https://github.com/lurk-lab/bellpepper/pull/22) to perform this more ergonomically by offering an explicitly infallible variant of `alloc`.
While I was there, I fixed a couple functions that required a `Result` for exactly no reason (I needed to use `clippy::unnecessary_wraps`, and they were lowering the signal-to-noise ratio of that tool).
- Removed uneeded `Result` …

refactor: Refactor error handling (mostly in circuits)

---

src/proof/nova.rs

The arecibo `DigestBuilder` PR (https://github.com/lurk-lab/arecibo/pull/40) changed `nova::PublicParams::setup()` to return a `Result`. This PR unbreaks `lurk-rs`, unwrapping here as we already do for `CompresedSNARK::setup()` on the next line.

Unwrap setup result.

---

examples/sha256.rs

For some reason, the `sha256` example benchmark was set to use `reduction_count = 100`, changing this `reduction_count=2` speeds up the proving about 12x.
Although this is not a great benchmark, and is quite noisy, I still think we should prioritize gradually removing the impediments to expected performance. From that perspective, I note that we *should* be able to handle `reduction_count=1` with a single iteration, but something still seems to prevent that.
My greater concern is: what aspect of process led to the inflated `rc=100` being introduced (and left unnoticed) here?
Before (`rc = 100`):
```
➜  lurk-rs git:(master) cargo run --example sha256 1 f5a5fd42d16a20302798ef6ed309979b43003d2320d9f0e8ea9831a92759fb4b false
Compiling lurk v0.2.0 (/Users/clwk/fil/lurk-rs)
Finished dev …
```

Use reduction_count=2 in sha256 example.

---

src/cli/backend.rs
src/cli/mod.rs
src/cli/repl.rs
tests/lurk-lib-tests.rs

The new REPL doesn't implement `assert-error` correctly. I noticed it while working on the `lem-integration` branch.
This PR fixes this issue and subjects the new REPL to the test suite from `lurk-lib`.
Extra: it also removes padding from the REPL because it's already done by `MultiFrame::from_frames`.

Fix new REPL

---

src/lem/circuit.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/macros.rs
src/lem/mod.rs
src/lem/path.rs
src/lem/pointers.rs
src/lem/slot.rs
src/lem/store.rs
src/lem/var_map.rs
src/lem/zstore.rs

* Use a stable `Store` for synthesis (literals have to be interned beforehand)
* Use a stable `GlobalAllocator` for synthesis (global constants have to be allocated beforehand)
* Adds several fixes to the step function, most of them related to finishing with proper errors
* Capture emissions during interpretation
* Replace `MatchVal` for a simpler `MatchSymbol`
* Unify and factor out the code for `MatchVal` and `MatchSymbol`
* Rename `Leaf` to `Atom` in the context of pointers
* Improve interning and fetching of strings and symbols in the `Store`
* Implement `ZStore` infra for LEM

Isolate some changes from #629

---

src/lem/circuit.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/macros.rs
src/lem/mod.rs
src/lem/slot.rs

As we've discussed on Zulip, slot-related entities should be named after their hashing arities and LEM operators should be called "cons" and "decons"

Give more meaningful names to LEM type variants and struct fields

---

src/lem/circuit.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/macros.rs
src/lem/mod.rs
src/lem/pointers.rs
src/lem/store.rs
src/lem/zstore.rs

* Reuse original `ZPtr` to define LEM's
* Get rid of `CtrlTag`
Closes #667

Reuse original `ZPtr`

---

src/lem/circuit.rs
src/lem/eval.rs
src/lem/macros.rs
src/lem/mod.rs
src/lem/store.rs

Hashing continuations should always involve 8 field elements. This PR makes fills the room with zeros like Lurk Alpha does.
This PR also fixes the fact that symbols were being reused in some continuations instead of their respective operators.

Make LEM's generated data compatible with Lurk Alpha

---

src/circuit/gadgets/pointer.rs
src/lem/circuit.rs

This PR makes `lem/circuit.rs` a bit more clean. Removes unnecessary functions in favour of already defined functions (like `AllocatedNum::alloc` and `AllocatedPtr::alloc`), removes unnecessary mutable borrows (some gadgets require a `mut cs` so there's no sense in sending a `&mut cs`), and makes namespaces more minimal

LEM circuit cleanup

---

.github/workflows/bench_pr_comment.yml
.github/workflows/ci.yml

This adds a new self-hosted GPU benchmark when the `!benchmark` command is commented on a PR. Unfortunately there doesn't seem to be a way to differentiate multiple comments other than using a different benchmark, so I've used `fibonacci` here.
Also removes some dependencies from CI as they are already installed via Docker on the self-host infra.

Add GPU benchmark comment

---

src/proof/supernova.rs

This PR removes the redundant padding code (forcibly making the padding frame a no-op). This is unnecessary, since a correctly-selected padding frame must always be a provable no-op already. This wasn't yet the case of reduction when this shim was used in development.

Remove padding hack.

---

src/circuit/circuit_frame.rs
src/circuit/gadgets/constraints.rs
src/coprocessor/mod.rs
src/proof/nova.rs

Closes #693.
This PR addresses the previous failure to properly destructure the standalone coprocessor circuit's arguments. This manifested in two ways:
1. The expr (the whole coprocessor expression rather than just the argument list) was returned in the case of an error.
2. The head itself was not checked against that specified by the `Lang` in the coprocessor's binding.
The second point is actually very important. Since we non-deterministically choose the next coprocessor circuit, it is critical that this circuit validates the context in which it is called. Put differently, the Lurk circuit contract requires that *every satisfiable circuit* correctly performs zero or more reduction steps. This allows for  no-ops (stuttering) in the allowed cases, for errors, for reduction-count > 1, and …

Correctly handle head/rest in standalone coprocessor circuit.

---

src/circuit/circuit_frame.rs
src/coprocessor/mod.rs
src/eval/reduction.rs
src/eval/tests/mod.rs
src/eval/tests/trie.rs
src/proof/nova.rs

This PR removes a spurious tail continuation introduced in #677.
This may resolve #686.

Remove unnecessary tail.

---

src/writer.rs

#364 introduced a more ergonomic way to input characters by enclosing them with single quotes.
This PR updates the writer code to print them in a way that reflects this ergonomic improvement.

Update char printing to use the newer syntax

---

src/circuit/circuit_frame.rs
src/circuit/gadgets/case.rs
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/pointer.rs
src/lem/circuit.rs
src/proof/nova.rs

- Replaced `AllocatedNum::alloc` with `AllocatedNum::alloc_infallible` throughout multiple files to simplify error handling and make code less verbose.

refactor: Refactor AllocatedNum allocation to infallible method

---

benches/end2end.rs
benches/fibonacci.rs
benches/sha256_ivc.rs
benches/synthesis.rs
clutch/src/lib.rs
examples/fibonacci.rs
examples/sha256_ivc.rs
examples/sha256_nivc.rs
fcomm/src/bin/fcomm.rs
fcomm/src/lib.rs
src/circuit/circuit_frame.rs
src/cli/repl.rs
src/eval/mod.rs
src/eval/tests/mod.rs
src/parser.rs
src/proof/groth16.rs
src/proof/nova.rs
src/repl.rs
src/store.rs
src/writer.rs

- Modifications to change mutable `Store` references to immutable across multiple files,
- Removal of  unused mutable `Store` instances in several test functions.
- Adjustments to several test functions to align with the change from mutable to immutable `Store` references.

refactor: Finish refactoring codebase to use immutable Store references

---

src/lem/circuit.rs
src/lem/pointers.rs

This PR does a small optimization to remove a clone from LEM's `Func::synthesize_frame`

Remove clone from `Func::synthesize_frame`

---

Cargo.toml
src/lem/var_map.rs

> [!Note]
> the same approach may well yield improvements elsewhere, I've just used it in this one place.
```
group                                                               fxhash                                 main
-----                                                               ------                                 ----
end2end_benchmark/end2end_go_base_nova/_10_0                        1.00    432.0±3.73ms          1.01    436.2±2.14ms
eval_benchmark/eval_go_base_bls12/_10_16                            1.00     10.6±0.03ms          1.45     15.3±0.05ms
eval_benchmark/eval_go_base_bls12/_10_160                           1.00    101.4±1.16ms          1.38    140.3±0.80ms
eval_benchmark/eval_go_base_pallas/_10_16                           1.00      9.2±0.08ms          1.50 …
```

tweak: change the HashMap hash algorithm in VarMap

---

benches/sha256.rs
examples/sha256_ivc.rs
examples/sha256_nivc.rs
examples/sha256_nivc_lem.rs
src/circuit/circuit_frame.rs
src/cli/lurk_proof.rs
src/coprocessor/mod.rs
src/coprocessor/sha256.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/multiframe.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs
src/public_parameters/disk_cache.rs
src/public_parameters/instance.rs
src/public_parameters/mem_cache.rs
src/public_parameters/mod.rs
tests/lurk-nivc-test.rs

This PR implements an NIVC example for LEM. It was also necessary to make `lurk::proof::supernova::circuit_cache_key` and `lurk::proof::nova::circuit_cache_key` generic on the `MultiFrameTrait` instead of hardcoding the call to `MultiFrame::blank`.
This PR also centralizes the implementation of the SHA-256 coprocessor because it was implemented in like 3 different places.

NIVC implementation for LEM

---

Cargo.toml
benches/end2end_lem.rs
src/lem/circuit.rs
src/lem/eval.rs
src/lem/pointers.rs
src/lem/var_map.rs

1. Benchmarking infra for LEM
2. A fix for the manual count of constraints
3. Some tweaks in the model that resulted in a reduction of ~400 constraints and some speed up in interpretation
4. An improvement in `VarMap`'s hashmap, the main responsible for cutting the 30x interpretation slowdown down to 17x
```text
end2end_benchmark/end2end_go_base_nova/_10_0
time:   [1.1855 s 1.1907 s 1.1949 s]
change: [-18.116% -17.702% -17.267%] (p = 0.00 < 0.05)
store_benchmark/store_go_base_bls12/_10_16
time:   [149.36 µs 149.40 µs 149.43 µs]
change: [+0.5304% +0.6076% +0.6923%] (p = 0.00 < 0.05)
Change within noise threshold.
store_benchmark/store_go_base_pallas/_10_16
time:   [158.67 µs 158.72 µs 158.76 µs]
change: [+3.2666% +3.5636% +3.8114%] (p = 0.00 < 0.05)
Performance …
```

Benchmarks for LEM

---

clutch/demo/chained-functional-commitment.lurk
clutch/demo/functional-commitment.lurk
fcomm/examples/Makefile
fcomm/examples/chained-request.json
fcomm/src/bin/fcomm.rs
fcomm/tests/makefile_tests.rs

- repairs the clutch tests,
- repairs the fcomm tests and execute `make clean` before running Makefile tests.

Repair nightly

---

src/lem/circuit.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/slot.rs
src/lem/tests/misc.rs

This PR replaces slot allocation for "less-than" operations with slot allocation for bit decomposition.
Slot allocating bit decomposition allows us to reuse bit decomposition in truncate operations, leading to 1k less constraints/auxiliaries

Slot allocation of bit decomposition

---

src/circuit/circuit_frame.rs
src/lem/multiframe.rs
src/lem/pointers.rs
src/lem/store.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs

Alpha's `Store::hash_expr`/`Store::hash_cont` and LEM's `Store::hash_ptr` are recursive and present a risk of exceeding the recursion depth limit if the Lurk data being content-addressed is too deep.
This PR assures that hydration is called right at the start of proving, which eliminates that risk in such scenarios.
This change doesn't bring relevant improvements in the proving benchmarks, which makes sense because the stores' hashing functions are fast enough by themselves even without hydration.
1. Introduce safe APIs for hashing pointers in contexts where hydration is not assumed to have been performed, such as interpretation
2. Set a chunk size limit of 256 for parallel hashing motivated by memory limit safety
Unexpectedly, the chunk size limit made LEM's hydration slightly faster: …

Safer hydration mechanics

---

Cargo.toml
benches/end2end_lem.rs
benches/fibonacci_lem.rs
benches/sha256_lem.rs
benches/synthesis_lem.rs
examples/sha256_nivc_lem.rs
lurk-macros/src/lib.rs
src/lem/tests/eval_tests.rs
src/proof/tests/nova_tests_lem.rs

[Post #738]
This PR implement the missing benchmarks for LEM. Here's the data I collected on my machine w.r.t. Alpha:
```
end2end_benchmark/end2end_go_base_nova/_10_0
time:   [1.1503 s 1.1551 s 1.1583 s]
change: [-19.754% -19.255% -18.666%] (p = 0.00 < 0.05)
```
```
synthesis/Synthesis-rc/5
time:   [7.2469 ms 7.2700 ms 7.2888 ms]
change: [-64.198% -64.043% -63.892%] (p = 0.00 < 0.05)
synthesis/Synthesis-rc/10
time:   [14.649 ms 14.656 ms 14.664 ms]
change: [-63.761% -63.730% -63.699%] (p = 0.00 < 0.05)
synthesis/Synthesis-rc/100
time:   [151.00 ms 151.11 ms 151.21 ms]
change: [-63.398% -63.337% -63.283%] (p = 0.00 < 0.05)
synthesis/Synthesis-rc/200
time:   [298.47 ms 299.53 ms 300.16 …
```

More LEM benchmarks and `Coproc` derivied implementations

---

.github/workflows/codecov.yml

- Implemented a new `Codecov` workflow for code coverage analysis.
- Configured the system to generate and upload coverage data to codecov.io when a push or pull request event occurs in the `master` branch.
- Used the grcov tool for test coverage data generation.

ci: Integrate Codecov for test coverage analysis

---

Cargo.toml
src/proof/supernova.rs

This PR addresses #695 by matching the `nova::Proof::verify` implementaton.
Do not merge until PR [#72](https://github.com/lurk-lab/arecibo/pull/72) in Arecibo is merged, and the `cargo.toml` change can be reverted.

match `supernova::Proof::verify` to `nova::Proof::verify`

---

benches/fibonacci_lem.rs

Without this change, benchmark output makes the `fibonacci_lem` bench look the same as the `fibonacci` bench, interfering with post-hoc analysis of benchmark runs.

Distinguish fibonacci_lem from fibonacci in bench name.

---

src/config.rs
src/lem/circuit.rs
src/lem/multiframe.rs
src/lem/slot.rs

This PR is a superset of #766.
> This PR implements parallel witness generation for LEM. On my machine I've got a 78% speedup with RC = 200 (the bigger the RC, the better). It's still significantly faster than parallel Lurk alpha
It also implements:
* Parallel witness generation for the slots
* A new canned config called `PARALLEL-SYNTHESIS`, from https://github.com/lurk-lab/lurk-rs/commit/230969bc1fa00747ad06016f982c484a6e47af88
It's our current best solution for LEM
Note: the big diff numbers is due to an extraction of an inner definition of `recurse` onto an outer `synthesize_block`, which makes `lem/circuit.rs` clearer and better suited for the implementation that this PR does.

Parallel witness generation for LEM

---

.github/workflows/gpu.yml

The current Vultr vGPU instance has issues with supporting the `cudaMallocAsync` function as seen in #595, so this PR switches GPU CI to run on a standalone Paperspace Nvidia A4000 instance. This also happens to lower the workflow time from 40 mins to 20.
Before: https://github.com/lurk-lab/lurk-rs/actions/runs/6581414040
After: https://github.com/samuelburnham/lurk-rs/actions/runs/6591626061
If the Vultr issue resolves we may eventually switch back to save a bit of compute cost.
Closes #595

ci: Switch GPU runner to Paperspace

---

examples/circom.rs
src/circuit/gadgets/circom/mod.rs
src/coprocessor/circom.rs
src/lem/eval.rs

[Post #755]
Coprocessor implementation and example file adapted to LEM
This PR also fixes the programmatically generated LEM code for when a `Lang` only has coprocessors with arity 0. Some LEM variables aren't used (such as `evaluated_args`) and thus should start with an underscore or simply not be initialized (such as `nil`).

LEM Circom

---

src/coprocessor/trie/mod.rs
src/proof/tests/nova_tests_lurk.rs

This adds a test for the positive lookup case (i.e. where something is found) of the Trie circuit. This missing test obscured that the bits of the path segment were backward (big-endian rather than little-endian). An empty trie is defined to find zero at the end of every path so can't be used to check this. I had a deferred the check to finalize this until the missing test could exercise it, but that test (apparently) never got written. Both issues should be fixed here.

Trie path fix

---

benches/fibonacci.rs

- Updated the `ProveParams` version from `ALPHA` to `LEM` in the Fibonacci benchmarking file.
- Fixes #800

fix: provide correct params to LEM version of fibonacci bench

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

- Enhanced CONTRIBUTING.md with specific instructions for maintainers about benchmarking.
- Established a Code of Conduct for the project in CODE_OF_CONDUCT.md, from https://www.contributor-covenant.org/
- Updated README.md by:
- Adding a direct link to Zulip forum for support discussions.
- Incorporating a scholarly reference about Lurk.
- Removing now obsolete Benchmarking section, transferred to CONTRIBUTING.md.

chore: Update project documentation and community guidelines

---

src/circuit/gadgets/pointer.rs
src/coprocessor/mod.rs
src/lem/circuit.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/mod.rs
src/lem/tests/eval_tests.rs
src/proof/tests/nova_tests_lem.rs

This PR is motivated by https://github.com/lurk-lab/lurk-rs/pull/752#discussion_r1359694110
It implements proper error handling for coprocessors in LEM and uses `DumbCoprocessor` to test the plumbing.

Fix coprocessor error handling/signaling in LEM

---

src/circuit/gadgets/pointer.rs
src/coprocessor/trie/mod.rs
src/lem/store.rs
src/lem/tests/eval_tests.rs
src/proof/tests/nova_tests_lem.rs
src/proof/tests/nova_tests_lurk.rs

This PR adds the implementations for the Trie coprocessor for LEM.
It also adds a missing test for the Trie coprocessor in Alpha and fixes a bug in the lookup circuit.

Trie implementations for LEM

---

Cargo.toml
benches/fibonacci_lem.rs
src/proof/nova.rs
src/proof/supernova.rs

This reverts commit 1ad6470d10f41ec94a016e0a6f0c8bcb9efb7ba3.
Replaces #807.

Revert "merge fib benchmarks (#784)"

---

src/lem/circuit.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/mod.rs
src/lem/multiframe.rs
src/lem/slot.rs
src/lem/tests/misc.rs

* Rename `Func` `slot` attribute to `slots_count`, which is clearer
* Fix commentary typo

Minor LEM changes

---

src/cli/zstore.rs
src/coprocessor/mod.rs
src/lem/circuit.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/macros.rs
src/lem/mod.rs
src/lem/multiframe.rs
src/lem/pointers.rs
src/lem/store.rs
src/lem/tests/eval_tests.rs
src/lem/tests/misc.rs
src/proof/tests/nova_tests_lem.rs

Changes:
* Expand LEM's expressiveness to produce that kind of data in the model
* Adjust the Store accordingly, providing the appropriate API to create such pointers directly
Performance:
* The store benchmarks are a bit worse because initiating a default Store now has the extra cost of computing a few poseidon hashes
* But hydration is better because the hardcoded tag check shim is gone
* No significant changes to evaluation or proving
Note: I tried an approach with `OnceCell`s. It made the store interning and hydration benchmarks have no change wrt `master`, but it backfired with a 2% slowdown in evaluation, which is worse than paying a small cost on the store startup.
```text
end2end_benchmark/end2end_go_base_nova/_10_0
time:   [1.1098 s 1.1130 s 1.1157 s]
change: [+0.1501% +0.4740% …
```

Eliminate hashing shims for hardcoded tags across the LEM codebase

---

src/cli/mod.rs
src/cli/repl.rs
src/cli/repl/meta_cmd.rs
src/lem/store.rs
src/parser/position.rs
src/syntax.rs
tests/lurk-lib-tests.rs

Adds a `--demo` flag to load files in demo mode.
This is better than the initial idea of a new command because it can reuse all the parameters that the `load` command already accepts.
Closes #757

Add a demo flag on the load command

---

.github/workflows/bench-deploy.yml
.github/workflows/merge-tests.yml

Bugs in #790:
- The `merge_group` bench wasn't generating a comparison due to a lack of shared `target/criterion` data
- The `merge_group` bench was always reporting a regression due to a syntax error
- The `bench-deploy` workflow wasn't generating benchmarks correctly as it was running in the wrong directory
Successful runs:
- Regression failure: https://github.com/lurk-lab/ci-lab/actions/runs/6711235126/job/18238175028
- Non-regression success: https://github.com/lurk-lab/ci-lab/actions/runs/6711704879/job/18239666659
NOTE: Do not merge until the `merge_group` bench (enabled on `pull_request` for testing) successfully reports a non-regression and then restores the previous trigger behavior.

ci: Fix bugs in `#790`

---

.github/workflows/bench-pr-comment.yml

Enables `!benchmark` and `!gpu-benchmark` comments to run on forked PRs.
Successful run: https://github.com/lurk-lab/ci-lab/actions/runs/6701467940/job/18208949422 from https://github.com/lurk-lab/ci-lab/pull/17
Closes #815

ci: Enable `issue_comment` actions on forked PRs

---

src/circuit/circuit_frame.rs
src/cli/commitment.rs
src/cli/repl.rs
src/cli/repl/meta_cmd.rs
src/coprocessor/mod.rs
src/coprocessor/sha256.rs
src/coprocessor/trie/mod.rs
src/eval/lang.rs
src/lem/circuit.rs
src/lem/interpreter.rs
src/lem/multiframe.rs
src/lem/store.rs
src/lem/tests/eval_tests.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs
src/proof/tests/nova_tests_lem.rs

Pointer hashing functions used to throw errors when the data needed for hashing wouldn't be found in the store. However, this indicates a malformed store, meaning that interning must have gone wrong somewhere else. So a straightforward panic is more adequate.
This simplifies a lot of calls to `Store::hash_ptr`, which were being `unwrap`d or `expect`d in many cases anyway.

Make `Ptr` hashing functions pure

---

src/eval/mod.rs
src/hash_witness.rs
src/store.rs
src/symbol.rs
src/z_data/z_store.rs

- Removed redundant and unused functions across multiple files including `hash_witness.rs`, `z_data/z_store.rs`, `eval/mod.rs`, and `symbol.rs`.
Remaining unused items are in the following categories:
- in a module we don't want to touch today (#804), and where removal needs some thought, e.g. `parse_code`, `parse_space`, `parse_line_comment`, `assert_all_paths_taken`, `construct`, `construct_strcons`,
- small utilities which removal wouldn't be significant, e.g. `is_evaluation`, `is_root_symbol`, `push_tag`, `push_symbol`, `push_default`, `to_z_expr`, `is_coprocessor`
- related to underused functionality we know we'll want to extend the use of: 
- supernova (`supernova_circuit_params`, `supernova_aux_params`, `supernova_public_params`), 
- opaque pointers (`intern_maybe_opaque_fun`, …

chore: remove dead code from multiple modules (easy)

---

src/cli/commitment.rs
src/cli/repl.rs
src/cli/zstore.rs
src/coprocessor/circom.rs
src/coprocessor/gadgets.rs
src/coprocessor/mod.rs
src/coprocessor/trie/mod.rs
src/eval/tests/mod.rs
src/lem/circuit.rs
src/lem/eval.rs
src/lem/pointers.rs
src/lem/store.rs
src/lem/tests/eval_tests.rs
src/store.rs
src/z_data/z_ptr.rs

* Several minor API improvements
* New doc-strings
* New helper gadgets for coprocessors authors, whose semantics are migrated from Alpha

More LEM API improvements

---

.github/workflows/bench-pr-comment.yml
benches/fibonacci_lem.rs

This PR adds the `LURK_BENCH_OUTPUT` env var, which enables customization of the `fibonacci_lem` `BenchmarkId` for differently formatted output types.
Problem: `boa-dev/criterion-compare-action` PR comment is printing incorrectly: https://github.com/lurk-lab/lurk-rs/pull/825#issuecomment-1789070013. `critcmp` can't compare benchmarks with different `BenchmarkId`'s, and our `fibonacci_lem` benchmark includes the commit hash in the ID.
Solution: Remove the commit hash for the `pr-comment` output type, and keep it for the other types for now.

ci: Parameterize `BenchmarkId` on output type in PR bench comments

---

src/public_parameters/mod.rs

fix: Port `serde_public_params_roundtrip` to LEM

---

src/proof/tests/mod.rs

There is a [deprecated warning](https://github.com/lurk-lab/arecibo/actions/runs/6716208822/job/18313683952?pr=89#step:7:811) in the result of the [check-lurk-compiles](https://github.com/lurk-lab/arecibo/blob/dev/.github/workflows/rust.yml#L39) job in [this pending pr](https://github.com/lurk-lab/arecibo/pull/89) due to a change that was made in bellpepper see: https://github.com/lurk-lab/bellpepper/pull/48
This change uses the new public getters for WitnessCS to resolve the deprecated warnings.

use non-deprecated getters for WitnessCS

---

Cargo.toml

- Downgraded the minimum Rust language version utilizable in the project.
- our MSRV was temporarily increased due to an erroneous increase in the dev branch of bellpepper. This was fixed in https://github.com/lurk-lab/bellpepper/pull/35

chore: Downgrade minimum Rust version to 1.71.1 (easy)

---

Cargo.toml
README.md
benches/end2end_lem.rs
clutch/src/main.rs
src/cli/circom.rs
src/cli/mod.rs
src/field.rs
src/lem/circuit.rs

- Follow-up of #774
- Swapped out `blstrs::Scalar` implementation in `src/field.rs` with pasta_curves::pallas::Scalar
- Readjusted tests to now run on the `pasta_curve` as opposed to the `blstrs`
- Updated `Cargo.toml` by removing `blstrs` from both the workspace and dev dependencies
- Removed the association of `blstrs/portable` from the `portable` feature in `Cargo.toml`

chore:: Refactor field tests to use pasta_curves instead of blstrs

---

.github/workflows/merge-tests.yml
benches/fibonacci_lem.rs

- Enables the `LURK_BENCH_OUTPUT="commit-comment"` env var option, which configures the benchmark metadata for `criterion-table` formatting.
- Moves the reduction count out of the `BenchmarkId` `name` and into the `BenchmarkGroup`, which separates bench run tables by `rc` in `criterion-table`.

ci: Compare `commit-comment` benches by `rc` group

---

README.md
src/lib.rs

The README isn't the best doc in the world, but it's better than the current void:
https://lurk-lab.github.io/lurk-rs/docs/lurk/index.html

doc: include README as module doc

---

.github/workflows/merge-tests.yml

Before: `131817664kB`
After: `125.711 GB RAM`

ci: Print `commit-comment` bench runner RAM in GB

---

benches/fibonacci_lem.rs

#852 broke GPU benches
https://github.com/lurk-lab/lurk-rs/actions/runs/6773544195/job/18408644257
This results in :
> thread 'main' panicked at benches/fibonacci_lem.rs:67:33:
> not yet implemented
This PR collapses the `gh-pages` job into the default case, making sure the unimplemented at this line isn't there to hit.

ci: fix GPU benches

---

src/cli/lurk_proof.rs
src/cli/repl/meta_cmd.rs
src/proof/nova.rs
src/public_parameters/mem_cache.rs
src/public_parameters/mod.rs

**Context**:
Developing [zeromorph](https://github.com/lurk-lab/arecibo/tree/zeromorph) forced me to abstract several Nova APIs over the used `EvaluationEngineTrait` (which was the point of the whole exercise). And it forced me to realize that Nova APIs that genericise over the group implementations, in order to represent the concept of a given curve cycle, become a lot simpler when they jointly abstract over the associated `EvaluationEngine`.
This insight led to https://github.com/microsoft/Nova/pull/234
**This PR**:
We prepare the code base from where it is now (hard-coding that the Evaluation Engine used in nova is the IPA, and requiring the corresponding idiosyncratic trait bound `CommitmentKeyExtTrait`) to something that's Zeromorph-ready (recognizing that any curve cycle may have …

refactor: Refactor trait requirements and update CurveCycleEquipped

---

.github/workflows/merge-tests.yml

- Updated GitHub workflows configuration to exclude `test_lurk_lib` during the 'ignored-only' run of Linux Tests.

ci: exclude test_lurk_lib from merge tests

---

.github/workflows/codecov.yml

- Utilize nightlies for scheduling the Codecov workflow instead of activating on push and pull requests to the master branch.
I was wrong, @arthurpaulino is right, this is taking too much time on our CI runners.

ci: Implement daily scheduled Codecov analysis

---

src/coprocessor/mod.rs
src/lem/eval.rs
src/lem/tests/eval_tests.rs
src/proof/tests/nova_tests_lem.rs

Prior to this PR, the CEK machine was completely unable to handle coprocessors that inadvertently halt the computation. Although that's not encouraged for coprocessors authors, we do want to fix such inability.
Extra: when testing the fix, I noticed that the model was wasting an iteration when evaluating a coprocessor call with no arguments. This PR also fixes that.

Properly handle halting coprocessors

---

.github/workflows/gpu-bench-workflow-dispatch.yml

This is a non-comparative version of the merge group benchmarks, enabling GPU benchmark testing on non-forked branches without opening a PR. It runs on whatever free `gpu-bench` runners are available and comments on the commit with the runner hardware and bench results.
Example run: https://github.com/lurk-lab/ci-lab/actions/runs/6788441299
Example output: https://github.com/lurk-lab/ci-lab/commit/ec33528aef7724ed7af7f7fcf949dbe9e8e07758#commitcomment-131943566
Future work:
- Link the job in the commit comment output so it's easier to track down the logs

ci: Add GPU benchmark on `workflow_dispatch`

---

Cargo.toml

This is fully expected to break on CI, but the full setup was tested locally.
> [!WARNING]  
> Sequencing for this PR:
> 1. this PR is reviewed ✅ despite CI status being ❎ 
> 2. https://github.com/lurk-lab/neptune/tree/dev is reset to https://github.com/lurk-lab/neptune/tree/dev_ng
> 3. companion Arecibo PR is merged ([#105](https://github.com/lurk-lab/arecibo/pull/105))
> 4. this PR's CI is re-run and succeeds
> 5. this PR is merged
> [!NOTE]
> If you want to test this at home:
> 1. checkout https://github.com/lurk-lab/neptune/tree/dev_ng (note the specific branch) to `$FOO/neptune`
> 2. checkout https://github.com/lurk-lab/arecibo/tree/with_abomonation_ng to `$FOO/arecibo` and apply instructions in the Note of https://github.com/lurk-lab/arecibo/pull/105
> 3. change the neptune …

chore: switch to abomonation_derive_ng

---

.github/workflows/bench-deploy.yml
.github/workflows/bench-pr-comment.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/gpu-ci.yml
.github/workflows/licenses-audits.yml
.github/workflows/links-check.yml
.github/workflows/merge-tests.yml
.github/workflows/nightly.yml
CONTRIBUTING.md
notes/reduction-notes.md

This PR prepares CI to run on `main`, as we are changing the default branch from `master` to `main`.
Marking as draft until the above process is ready.

chore: Rename default branch from `master` to `main`

---

src/num.rs

- Enhanced property testing coverage and introduced new tests for `U64` and `Scalar` types.
- Provided comprehensive test scenarios including basic operations, assertions, checking sign, and "lesser" properties.
- Improved coverage for scalars and u64, encompassing overflow/underflow cases and edge conditions.
Closes #52

test: Enhance `Num<Fr>` testing

---

demo/bank.lurk
demo/vdf.lurk
src/cli/repl.rs
src/cli/repl/meta_cmd.rs
src/lem/multiframe.rs
tests/lurk-cli-tests.rs
tests/lurk-files-tests.rs

* Make the REPL raise errors properly instead of just printing locally so loading files
with mistakes causes an unsuccessful termination
* Fix errors on some of our demos due to the fix above
* Fix the chain meta command so it persists commitments with the right secret
* Assert that the output of the padded frame is the same as the one from the original last frame

Make some assertions more conservative

---

src/cli/commitment.rs
src/cli/lurk_proof.rs
src/cli/mod.rs
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs
src/cli/zstore.rs

This PR implements the `pack` and `unpack` commands, which are meant to support proof sharing safely.
Proof meta files now carry a `ZDag`, which are incapable of holding commitment secrets *by definition*, mitigating a concern raised in [Zulip](https://zulip.lurk-lab.com/#narrow/stream/17-lurk/topic/Using.20Lurk.20in.20a.20protocol/near/127889)

Implement `pack` and `unpack` commands

---

src/lem/pointers.rs
src/lem/store.rs

This PR is a follow up to #878 because I realized that we didn't have tests for the basic cases of `Store::hash_ptr`.
This PR also shows how to achieve opaque functionality with `ZPtr`s.

Create tests for basic hashing; add an API to create opaque pointers

---

Cargo.toml
src/proof/nova.rs
src/proof/supernova.rs

- companion PR to https://github.com/lurk-lab/arecibo/pull/115
- Renamed methods within `RelaxedR1CSSNARKTrait` in `src/proof/nova.rs`
- Updated the method name in `src/proof/supernova.rs` from `default_commitment_key_hint` to `default_ck_hint`

refactor: Refactor method names and update nova-snark branch

---

Cargo.toml
src/hash.rs
src/lem/store.rs
src/store.rs

Updates to match https://github.com/Manishearth/elsa/pull/67

chore: dependency updates, incl. elsa

---

src/field.rs
src/lem/circuit.rs
src/lem/multiframe.rs
src/lem/store.rs

I got some improvements for synthesis on my machine:
```text
synthesis/Synthesis-rc/8                                                                            
time:   [6.2669 ms 6.4224 ms 6.5533 ms]
change: [-6.2341% -3.8673% -1.8713%] (p = 0.00 < 0.05)
synthesis/Synthesis-rc/16                                                                            
time:   [4.7671 ms 4.8198 ms 4.8714 ms]
change: [-2.9545% -1.6521% -0.4143%] (p = 0.02 < 0.05)
Change within noise threshold.
synthesis/Synthesis-rc/24                                                                            
time:   [6.7224 ms 6.7568 ms 6.7920 ms]
change: [-1.6682% -0.9685% -0.2239%] (p = 0.01 < 0.05)
Change within noise threshold.
synthesis/Synthesis-rc/32 …
```

Start slots witnesses with known capacities

---

src/lem/circuit.rs
src/lem/interpreter.rs
src/lem/macros.rs
src/lem/mod.rs

This PR implements LEM units as Rust closures for general debugging or data collection purposes.
For example, if we add `unit(...);` in the model, as in:
```rust
// binops
let (op) = get_binop(head);
let op_is_nil = eq_tag(op, nil);
if !op_is_nil {
if !rest_is_nil {
let (arg1, more) = decons2(rest);
let more_is_nil = eq_tag(more, nil);
if !more_is_nil {
unit(|| println!("starting a binop"));
let cont: Cont::Binop = cons4(op, env, more, cont);
return (arg1, env, cont, ret);
}
return (expr, env, err, errctrl);
}
return (expr, env, err, errctrl);
}
```
The interpreter will run that closure and this is what we see in the REPL:
```text
user> (+ 1 1)
starting a binop
[3 iterations] => 2
```
With that closure we can do tracing etc. The goal is to move towards the level of …

Add `Op::Unit` for general purpose debugging or data collection

---

src/lem/eval.rs
src/proof/mod.rs

This PR removes the premature creation of a padding frame during evaluation, which is already performed later, if needed, during the creation of the multi-frames.
It targets an item of #716
Closes #729

Remove premature padding from evaluation

---

src/lem/eval.rs
src/lem/macros.rs
src/lem/mod.rs

This PR makes some parts of our model more easily readable by introducing specialized APIs which are more idiomatic for situations in which we don't want to use the macros.

Create and use more idiomatic APIs for LEM types

---

benches/synthesis.rs
src/lem/multiframe.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs

* Mitigate the overloading of "reduction_count" across the folding config and the number of frames in a MultiFrame
* Drop the duplicated "reduction count" information that was passed to `MultiFrameTrait::from_frames`
* Drop the unused `make_dummy`
Context: when we only had IVC, the number of frames in a `MultiFrame` was always exactly the `reduction_count`. But now that we have NIVC and some `MultiFrame`s can have different numbers of frames (the ones related to coprocessors only have one frame), the `MultiFrame`'s `reduction_count` attribute became confusing. This PR changes its name to `num_frames`.
Targets an item of #716

Improving some parts of the proving pipeline

---

.github/workflows/merge-tests.yml

Parses the `criterion-table` output to detect a slowdown >= 10%, then opens an issue rather than failing the job so we can revert the merged PR if desired. This makes it easier to handle spurious errors and false positives, e.g. if there are changes to the `fibonacci` benchmark or the workflow file itself.
Example run:
https://github.com/lurk-lab/ci-lab/issues/37
> [!WARNING]  
> Once this lands, we'll need to be vigilant about addressing such regressions quickly, ideally before merging any further PRs. One option is to send automated emails to maintainers via https://github.com/dawidd6/action-send-mail, which could be the next PR.
Closes #837

ci: Fix perf regression check on `merge_group` benchmarks

---

.github/workflows/merge-tests.yml
benches/fibonacci.rs
benches/justfile

Commits successful PR benchmark results to `gh-pages` as `<${{ github.sha }}>-<$GPU_MODEL>.json`. When the next PR runs the benchmark workflow, it will restore the previously saved `gh-pages` file as the new base benchmark if it still exists and was run on the same GPU. Then the PR benchmark will run and compare to the base benchmark as usual.
On a cache hit, this should save 13-20 minutes on the `merge_group` GPU bench workflow, down from 35-40 minutes to the low 20s. The GPU benchmarks would currently be the bottleneck on merging a PR if made a required status check, but the cache would alleviate this by bringing them into the ballpark of the other `merge_group` tests. 
Cache hit: https://github.com/lurk-lab/ci-lab/actions/runs/6912455892
Cache miss: …

ci: Cache PR benchmarks on `gh-pages`

---

benches/sha256.rs
examples/sha256_nivc.rs
src/lem/eval.rs
src/lem/multiframe.rs
src/lem/tests/eval_tests.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs

* Extract `pad_frames` logic to avoid code duplication
* Rename `get_evaluation_frames` to `build_frames`
* Eliminate padding predicate from `build_frames`
* Introduce `EvalConfig` to avoid plumbing with bools
* Use `EvalConfig` to tell whether `build_frames` is called in an IVC or NIVC context
* Use the above to fix a bug in the SuperNova prover that would cause it to generate frames with IVC characteristics
Context: padding is no longer a responsibility of the evaluation phase so `build_frames` doesn't need to know about a padding predicate
This is an alternative solution to #906 after the insights provided by #909

Fix more pipeline rough edges

---

.github/workflows/bench-deploy.yml
.github/workflows/merge-tests.yml

#907 introduced a bug by appending the `$GPU_NAME` env var to the benchmark JSON filename, which contained spaces and thus caused errors in https://github.com/lurk-lab/lurk-rs/actions/runs/6938182407/job/18873513559. This PR fixes the bug by only using the GPU model name (e.g. `4070` or `L4`).
Also fixes an issue where #907 changed the `justfile` bench location, but forgot to update the `bench-deploy` action accordingly.

ci: Fix `merge_group` cache key bug in filename

---

src/lem/tests/mod.rs
src/lem/tests/nivc_stutter.rs

In an NIVC context, we want to assert that:
* The Lurk step `Func` stutters on inputs meant for coprocessor `Func`s
* Coprocessor `Func`s can't reduce inputs meant for Lurk step `Func`
* Coprocessor `Func`s can only reduce inputs marked with their names

Add a test for NIVC stuttering

---

Cargo.toml
src/cli/lurk_proof.rs
src/cli/repl/meta_cmd.rs
src/lem/multiframe.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs
src/public_parameters/disk_cache.rs
src/public_parameters/instance.rs
src/public_parameters/mem_cache.rs
src/public_parameters/mod.rs

Companion Arecibo PR:
https://github.com/lurk-lab/arecibo/pull/133
- Adapted the codebase to replace the `Group` types and traits with `Engine`, and replaced `G1` and `G2` with `E1` and `E2`.
- Updated the trait `EvaluationEngineTrait<G>` and `RelaxedR1CSSNARKTrait` along with type aliases to reflect these changes.
- Modified the `CurveCycleEquipped` implementation for `bn256::Scalar` and `pallas::Scalar`.
- Made necessary adjustments to the aid functions and type aliases related to `NovaProver` for compatibility with the new group types.
- Made changes in the SuperNova proving system to accommodate new `Engine` types.

refactor: Refactor to adpt to Arecibo changes in PR 133

---

Cargo.toml
src/field.rs
src/lem/multiframe.rs
src/proof/nova.rs

- companion PR of https://github.com/lurk-lab/arecibo/pull/135
- Replaced the usage of `nova::provider::bn256_grumpkin` with `halo2curves` in `src/lem/multiframe.rs`, `src/proof/nova.rs`, and `src/field.rs` since the nova module is now private,
- Updated tests in `src/lem/multiframe.rs` to use the `halo2curves` library,
- Replaced `bn256_grumpkin::bn256` with `Bn256Engine` and redefined `CurveCycleEquipped` for `Bn256Scalar` in `src/proof/nova.rs`.
- Added `halo2curves` to the list of dependencies in `Cargo.toml` and updated the `LurkField` implementation in `src/field.rs`.

chore: Replace nova::bn256_grumpkin with halo2curves library

---

.github/workflows/bench-pr-comment.yml
.github/workflows/gpu-bench-workflow-dispatch.yml

- Fixes an issue where the manual `workflow_dispatch` action wasn't finding the benchmark output for `criterion-table` in e.g. https://github.com/lurk-lab/lurk-rs/commit/4bc6fa197eeb5c7b82ce246ebccd0895e424acc3#commitcomment-133745609 due to the `justfile` changes of #907 
- Fixes an issue where the PR comment benchmark wasn't loading the `bench.env` file correctly, thus always using the default `rc=100` value in e.g. https://github.com/lurk-lab/lurk-rs/pull/927#issuecomment-1830868519. It should now be possible for PR authors to configure which RC's they want the benchmark to run on by committing the `bench.env` with different `LURK_RC` values.

ci: Fix `workflow_dispatch` output and `issue_comment` env load

---

src/lem/multiframe.rs

This PR recovers a mechanic from Alpha's witness generation that wasn't integrated in LEM (my bad)

Actually use precomputed cached witness

---

src/lem/multiframe.rs

This reverts commit 141b042908c16b86e2f078b8528e30efa99be16a.
(which breaks in several places)

Revert "Actually use precomputed cached witness (#928)"

---

src/lem/multiframe.rs
src/proof/mod.rs
src/proof/nova.rs

This PR is a second attempt after the failure of #928 (reverted in #931).
#928 was returning the wrong output because LEM doesn't allocate the output at the end.
So this PR allows `MultiFrameTrait` implementers to cache their witnesses internally, using whichever data format they want. LEM's `MultiFrame` does so by caching the `WitnessCS` and the output (the vector of allocated numbers).
With that available, LEM can now make proper use of cached witnesses.

Actually use precomputed witness

---

src/lem/circuit.rs
src/lem/interpreter.rs
src/lem/slot.rs

This PR simplifies slot data, and also makes it more flexible. The flexibility is important for a later change to the environments, where we want to use hash4 on components that sometimes are plain numbers, and no tags.

Simplified slot data

---

src/proof/nova.rs

This PR decreases the likelihood of the folding steps having to wait for `MultiFrame` locks to be released, making CPU and GPU work better in parallel. This effect is arguably more relevant for longer computations, but we can also notice improvements on shorter ones. The following tables show adjusted throughput up to 3 folding steps:
**Before**
```text
┌────────────┬──────────────┬─────────────┬─────────────┐
│ rc\n_folds │ 1            │ 2           │ 3           │
├────────────┼──────────────┼─────────────┼─────────────┤
│        100 │ 584.62±10.91 │ 549.11±4.67 │ 545.78±4.78 │
│        300 │  714.55±6.30 │ 657.31±1.24 │ 654.20±1.34 │
│        500 │  672.40±2.13 │ 622.96±2.73 │ 620.16±1.55 │
│        700 │  608.16±2.49 │ 571.52±2.55 │ 565.46±1.13 │
│        900 │  617.39±3.31 │ …
```

Remove parallel acquirement of locks for `MultiFrame` witness caching

---

.github/workflows/merge-tests.yml

It appears that env vars aren't saved to `$GITHUB_ENV` until the script completes, so this workaround binds to a local var for use within the script and then exports for later steps.
Fixes #946

ci: Fix cache ID not writing to env var

---

Cargo.toml
src/proof/supernova.rs

This is a companion PR to [arecibo#175](https://github.com/lurk-lab/arecibo/pull/175) which changes the `supernova::RecursiveSNARK::verify` interface by removing its dependence on `circuit_index`.
TODO before merge:
- after [arecibo#175](https://github.com/lurk-lab/arecibo/pull/175) merges, revert `Cargo.toml` change

Fix call to `supernova::RecursiveSNARK::verify`

---

src/lem/eval.rs
src/lem/interpreter.rs
src/lem/multiframe.rs
src/lem/pointers.rs

Remove misleading vestigial `Ptr::dummy` API.
We should use `Store::dummy` instead.

Remove `Ptr::dummy` API

---

.github/workflows/bench-pr-comment.yml

Fixes an issue where the `!benchmark` and `!gpu-benchmark` commands would always compare with `main`, regardless of the base branch of the PR. Now the workflow correctly obtains the base branch and runs the comparative bench against it.

ci: Fix benchmark comment on PRs to non-default branch

---

Cargo.toml
examples/sha256_ivc.rs
examples/sha256_nivc.rs
src/error.rs
src/proof/supernova.rs
src/public_parameters/mod.rs

This PR adds support the SuperNova CompressedSnark (coming in https://github.com/lurk-lab/arecibo/pull/131), and also includes CompressedSNARK timing to both the IVC and NIVC sha256 examples.
[edit: I moved the prior Serialization issue of this PR at https://gist.github.com/huitseeker/d642398f7eddd702761577a02e7202b8 ]

Support SuperNova CompressedSNARK.

---

src/lem/circuit.rs
src/lem/interpreter.rs
src/lem/var_map.rs

This PR simplifies how call hints work. A bindings field is added, which is not the full binding, but only the necessary bindings for call and cproc. This field can be used by all sorts of operations that needs to save values. I'm planning on adding another call operation, for extern calls, so this is important

Simplified `Func` and `Cproc` call

---

src/lem/eval.rs

Use expect_test to make assertions about circuit properties

---

src/coprocessor/circom.rs
src/coprocessor/gadgets.rs
src/coprocessor/mod.rs
src/coprocessor/trie/mod.rs
src/lem/circuit.rs
src/lem/multiframe.rs

* Make `GlobalAllocator` use a `FrozenMap` instead of a `HashMap` so we never need a mutable reference to it
* Allocations now happen in-place if not memoized
Closes #980

refactor: revamp `GlobalAllocator`

---

benches/fibonacci.rs
examples/fibonacci.rs
src/lem/eval.rs
src/lem/store.rs
src/lem/tests/eval_tests.rs
src/proof/tests/nova_tests_lem.rs
src/state.rs

This PR changes the way application and environments work.
First, the most important: the environments. The way Lurk used to work is that every time an operation changed an environment, you'd have to push a continuation that would recover the unchanged environment. This was an invariant that absolutely had to be followed, because we would not save the environment for the argument of the function, instead relying on the environment that was returned. That is, it was the responsibility of whoever modified the environment to recover it after reducing the expression, not the responsibility of the whoever must save expressions to the continuation to also save the running environment. This was quite unusual, so I decided to go with the more common approach, of saving environments in …

New application

---

benches/end2end.rs
examples/circom.rs
examples/sha256_ivc.rs
examples/sha256_nivc.rs
src/cli/lurk_proof.rs
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs

* Include the number of steps in the Nova proof type so it can be used for verification
* Remove the need to pass an extra input for `RecursiveSNARKTrait::verify`
* `RecursiveSNARKTrait` no longer needs an arbitrary `ProofOutput` since the index of the last circuit is no longer needed for SuperNova proof verification
Closes #954

Refactor: fix asymmetries between Nova and SuperNova APIs

---

Cargo.toml
examples/tp_table.rs

Add example to measure throughput in it/s (raw and adjusted) across different rcs and number of folding steps
This is a PoC that we might want to later integrate with `criterion` somehow.
On a short run with `LURK_RC=8,16 LURK_N_FOLDS=2 cargo run --release --example tp_table`, it prints:
```text
Raw throughput
┌────────────┬─────────────┬────────────┬────────────┐
│ rc\n_folds │ 0           │ 1          │ 2          │
├────────────┼─────────────┼────────────┼────────────┤
│          8 │  85.61±3.15 │ 64.45±0.92 │ 56.22±0.68 │
│         16 │ 111.48±2.30 │ 77.47±0.70 │ 67.54±0.61 │
└────────────┴─────────────┴────────────┴────────────┘
Adjusted throughput
┌────────────┬────────────┬────────────┐
│ rc\n_folds │ 1          │ 2          │
├────────────┼────────────┼────────────┤
│          8 │ …
```

New throughput performance example

---

Cargo.toml

Requires https://github.com/lurk-lab/arecibo/pull/187 upstream

GPU accelerated Grumpkin MSM

---

benches/bench.env

- dtolnay/rust-toolchain adds cargo to the GITHUB_PATH, which isn't carried to the justfile environment apparently: https://github.com/dtolnay/rust-toolchain/blob/be73d7920c329f220ce78e0234b8f96b7ae60248/action.yml#L66C16-L66C49
- Added PATH settings to the bench environment file to improve its usability
Closes #1001

chore: Repair fibonacci bench

---

.github/workflows/ci.yml
benches/bench.env
benches/justfile

Should fix GPU bench context not getting passed to `just` in https://github.com/lurk-lab/lurk-rs/actions/runs/7303184411/job/19903188606
Successful run: https://github.com/lurk-lab/ci-lab/actions/runs/7303550106/job/19904246258

ci: Fix justfile and upgrade hardware

---

.github/dependabot.yml
Cargo.toml

- Updated Dependabot configuration
- Upgraded various package versions including `generic-array`, `itertools`, and `rustyline-derive`
Replaces #1008

chore: Update Rust dependencies and Dependabot configuration

---

examples/sha256_ivc.rs
examples/sha256_nivc.rs
src/proof/supernova.rs

- Added serialization for the compressed proof using bincode in `sha256_nivc.rs`
- Implemented computation and display of serialized compressed proof size
- Introduced `serde` bound attribute to the `Proof` enum in `supernova.rs`
Fixes #1006

fix: allow SuperNova compressed proof serialization and size computation

---

src/cli/backend.rs
src/cli/mod.rs
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs

* Remove the hardcoded Pallas field from the REPL
* Enable the use of BN256/Grumpkin cycle
Addresses the second item of #533

Chore: generalize the REPL field and enable BN256

---

benches/sha256.rs
examples/sha256_nivc.rs
src/cli/mod.rs
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs
src/lem/eval.rs
src/lem/multiframe.rs
src/lem/tests/eval_tests.rs
src/lem/tests/nivc_steps.rs

* Remove hardcoded Coproc occurrences from the REPL implementation
* Use Coproc on the top-level call
* Fix a non-generalized leftover from #1017
Addresses the third item of #533

Chore: generalize the REPL's Lang

---

.github/CODEOWNERS

~~This PR needs the [`lurk-lem`](https://github.com/orgs/lurk-lab/teams/lurk-lem) team to be renamed to `lurk-eval`. Its description should be "Review approval for lem/eval.rs"~~

Request review from `lurk-eval` for changes in `src/lem/eval.rs`

---

benches/common/fib.rs
demo/bank.lurk
demo/chained-functional-commitment.lurk
demo/vdf.lurk
src/lem/eval.rs
src/lem/store.rs
src/lem/tests/eval_tests.rs
src/proof/tests/nova_tests_lem.rs
src/tag.rs

This PR simplifies recursive environments. Now, instead of it taking an environment itself, the tag for the symbol is changed to denote a recursive variable. Although we can't get mutual recursion like this, there's a possible fix:
```scheme
(letrec ((f A) (g B))
C)
```
can be transformed into
```scheme
(letrec ((f (letrec ((g B)) A)))
(letrec ((g B)) C))
```
while reducing, which will achieve mutual recursion. This will, however, add some overhead to non-mutually recursive functions. But again, this can be mitigated if we take the memoset approach to `letrec`.
Now, because of the simplification, it is possible to do 3 lookups per step without adding any slots. This greatly increases performance. `(fib 20)` goes from 613 iterations to 390, almost half the number of iterations

Multiple lookups, simpler rec environment

---

src/cli/field_data.rs
src/coprocessor/circom.rs
src/coprocessor/mod.rs
src/coprocessor/trie/mod.rs
src/eval/lang.rs
src/eval/mod.rs
src/field.rs
src/lem/circuit.rs
src/lem/eval.rs
src/parser/error.rs
src/public_parameters/disk_cache.rs

Bounds on structs are generally not preferable (see e.g. [ref](https://stackoverflow.com/questions/49229332/should-trait-bounds-be-duplicated-in-struct-and-impl)), yet they're present in many places in the code base, even on structs which operation is purely parametric in their contents. This is in part because trait bounds on structs are viral (they force any super-structure that reuses the struct to replicate them).
This PR removes some unneeded instances.

Remove uneeded bounds on structs

---

src/lem/multiframe.rs
src/proof/nova.rs
src/proof/supernova.rs

* MultiFrames with PC=0 have their witnesses cached just like in the IVC pipeline
* MultiFrames with PC!=0 have their witnesses cached in parallel due to limited size
(agnostic to RC) and poor internal parallelism
These are the times (in milliseconds) of proving when running `cargo run --release --example sha256_nivc`:
* `main`: 871, 882, 883 and 892
* this branch: 864, 859, 852 and 878
Closes #937

Chore: folding in parallel with witness generation for NIVC

---

Cargo.toml

- The `halo2curves` dependency has been upgraded to version `0.6.0`.
Companion PR of
- https://github.com/lurk-lab/arecibo/pull/250
- https://github.com/lurk-lab/grumpkin-msm/pull/11

chore: Update halo2curves and other dependencies

---

.clippy.toml
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/pointer.rs
src/coprocessor/memoset/mod.rs
src/coprocessor/memoset/multiset.rs
src/coprocessor/memoset/query.rs
src/coprocessor/mod.rs
src/lem/store.rs

This PR implements a MemoSet proof-of-concept, sufficient to implement mutually recursive coprocessors ('coroutines') using Lurk calling conventions. It does not integrate this ability into the Lurk reduction, nor provide concrete coprocessors sufficient to package this work into existing NIVC proofs.
The transcript is produced in the most straightforward way that can work, using literal Lurk data. It is worth noting that this dramatically simplified the already difficult task of getting an evaluation-time and proof-time transcript to match. There are undoubtedly optimization opportunities via reducing hashing costs. Because of the debugging benefit of the current approach, it is likely worth refactoring to something less legible only carefully. Ideally, it would be a simple configuration …

Implement MemoSet.

---

benches/common/fib.rs
demo/bank.lurk
demo/chained-functional-commitment.lurk
demo/functional-commitment.lurk
demo/protocol.lurk
demo/vdf.lurk
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs
src/cli/zstore.rs
src/lem/circuit.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/macros.rs
src/lem/mod.rs
src/lem/multiframe.rs
src/lem/slot.rs
src/lem/store.rs
src/lem/tests/eval_tests.rs
src/proof/tests/nova_tests_lem.rs
src/state.rs
src/tag.rs
tests/lurk-cli-tests.rs

This PR optimizes environments. Now, they're specialized data structures with its own tag `Env`. Empty environments are 0 valued environments, and otherwise they are a hash of size 4, the first element being the symbol payload, the second and third elements being the corresponding value's tag and payload, and the fourth element, the tail environment's payload. Doing this means lookups now take a single hash4, which allows us to do 8 lookups per step!
In the earlier PR, we simplified recursive envs by tagging symbols with a special tag to signal it came from a letrec. Now, because we don't have tags in symbols, some other strategy is needed. This is why I'm now tagging functions with a special recursive tag. It's important to note that this tag only appears in functions inside environment, …

Environment optimization

---

.github/workflows/gpu-ci.yml
Cargo.toml
lurk-macros/Cargo.toml
lurk-macros/src/lib.rs
lurk-metrics/Cargo.toml

- Refined GitHub GPU CI workflow by removing OpenCL Rust tests and enabling only CUDA tests
- Revamped package settings to workspace level across the GitHub repository, implemented in `lurk-macros`, `lurk-metrics` and `Cargo.toml`
- Removed specific dependencies `pasta-msm` and `grumpkin-msm` from `Cargo.toml`,
- Reordered the features in `Cargo.toml`, removed `opencl` and some deps off `portable` for better maintainability
- Cleaned up minor formatting issue in 'lurk-macros/src/lib.rs'

chore: Drop OpenCL, and refactor Cargo.toml for workspace use

---

notes/soundness-notes.md

Found a few errors I fixed in notes/soundness-notes.md while reading it.
Hope I could be of any help.

chore: proofreading soundness-nodes.md

---

.github/workflows/bench-deploy.yml
.github/workflows/gpu-bench-merge-regression.yml

Fixes bugs that surfaced in #964, e.g. the erroneous #1055

ci: Fix GPU merge regression check action

---

.github/workflows/gpu-ci.yml

Fixes the issue described in https://github.com/lurk-lab/ci-workflows/issues/27
Tested in https://github.com/lurk-lab/ci-lab/pull/49 via https://github.com/lurk-lab/ci-lab/actions/runs/7543985016
> [!NOTE]
> Merge after https://github.com/lurk-lab/ci-workflows/pull/28

ci: Fix GPU CI required status check

---

src/coroutine/memoset/demo.rs
src/coroutine/memoset/mod.rs
src/coroutine/memoset/query.rs

As noted in a comment to #1004 (https://github.com/lurk-lab/lurk-rs/pull/1004#discussion_r1452834234), we can avoid the `sort` by accumulating insertions in a `HashMap`. This PR does that.
UPDATE: As I noted in a comment, there is still some sorting, just 'less' — sorry for any confusion.
UPDATE 2: Last sorting has been removed.
Base branch is currently #1048, but the intention is to only merge after that one. Hopefully GH will correctly update base branch of this PR then.

Accumulate insertions in HashMap to avoid sort.

---

.github/workflows/nightly.yml
README.md

- Renames the nightly workflow test in '.github/workflows/nightly.yml'
- detects unused dependencies,
- detects Rust version becoming stale w.r.t. stable
Fixes #983

ci: nightly GitHub Action workflow

---

src/lem/tests/eval_tests.rs
src/num.rs

@gabriel-barrett, this is the reproducible example of the issue I mentioned recently.
```
failures:
lem::tests::eval_tests::char_coercion
lem::tests::eval_tests::commit_nil
lem::tests::eval_tests::commitment_value
lem::tests::eval_tests::test_trie_lang
```

[Issue#1018] Reproducible example [DO NOT MERGE]

---

src/coroutine/memoset/demo.rs
src/coroutine/memoset/mod.rs

This PR makes whether or not to add internal insertions to the transcript configurable. Until we determine that it is definitely safe to omit, we should preserve the ability not to. You can see the performance impact on the test examples below.
```
fn test_query_with_internal_insertion_transcript() {
test_query_aux(
true,
expect!["10826"],
expect!["10859"],
expect!["11408"],
expect!["11445"],
)
}
#[test]
fn test_query_without_internal_insertion_transcript() {
test_query_aux(
false,
expect!["9381"],
expect!["9414"],
expect!["9963"],
expect!["10000"],
)
}
```

Make internal insertion transcript optional with config.

---

benches/end2end.rs
benches/fibonacci.rs
benches/sha256.rs
examples/sha256_nivc.rs
examples/tp_table.rs
src/cli/lurk_proof.rs
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs
src/lem/multiframe.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs

This PR changes the prover API quite a bit
1) Prover is generic over a `FrameLike` type, no more hardcoded to the Multiframe
2) Prover is no more tied to coprocessors
3) Prover no longer has a function over `Frame`s
This PR was motivated by the work on systems. I think the API today is too rigid and I'm trying to make it more flexible. I've removed things which I believe has no business being inside the prover, like coprocessors, since this is a property of the multiframe, which is subject to change. Frames are also not important to the prover, only the multiframe is. Plus, with coroutines we might not build a vector of frames anymore, but a more complicated structure. We will need to translate that structure into a ordered multiframe structure however. As of now, the prove function …

Generic `Prover`

---

Cargo.toml
_typos.toml
lurk-metrics/src/lib.rs
lurk-metrics/src/recorder.rs
rust-toolchain.toml

chore: dependency updates

---

.github/workflows/gpu-ci.yml
src/circuit/circuit_frame.rs
src/circuit/gadgets/constraints.rs
src/coprocessor/gadgets.rs
src/coprocessor/trie/mod.rs
src/coroutine/memoset/demo.rs
src/coroutine/memoset/mod.rs
src/coroutine/memoset/query.rs
src/eval/lang.rs
src/field.rs
src/lem/circuit.rs
src/lem/eval.rs
src/lem/multiframe.rs
src/lem/store.rs
src/lem/tests/misc.rs
src/lem/tests/nivc_steps.rs
src/num.rs
src/parser/base.rs
src/parser/string.rs
src/parser/syntax.rs
src/proof/tests/nova_tests_lem.rs
src/public_parameters/mod.rs
src/symbol.rs
src/z_data/serde/mod.rs
src/z_data/z_cont.rs
src/z_data/z_expr.rs
src/z_data/z_ptr.rs
src/z_data/z_store.rs

Partially fixes https://github.com/lurk-lab/lurk-rs/issues/1018
I think PR is finally ready for review. 
`LurkField` is changed to Bn256 in the majority of the unit-tests where it could be potentially useful for solidity-verifier to produce the test-vectors, so the field has not been changed in benches and examples - as they are more client-facing programs that somebody can already rely on, so this left for a future PR(s).
Special thanks to @gabriel-barrett !

Use Bn256/Grumpkin curves as a default setting

---

src/coroutine/memoset/demo.rs
src/coroutine/memoset/mod.rs
src/coroutine/memoset/query.rs

This PR adds and exposes the minimal structure that should allow for creation of distinct circuits for each coroutine. This will be required in order to support actual NIVC proving.
Future work should include:
- minimizing or at least reducing expensive clones. This may require revisiting the underlying data structures (the multiset, the queries map, etc.) to either allow for better sharing — or to accumulate the circuit-specific parts in a way that allows them to be more cheaply separated when needed.
- supporting the equivalent of `rc` per coroutine circuit. Currently, the circuit will just contain exactly as many prove-and-remove steps as required for the actual computation witnessed. In reality, we need a fixed number per circuit — such that multiple circuits can be used if needed, …

Separate coroutine circuits.

---

Cargo.toml

- Removes several dependencies from Cargo.toml including `ahash`, `metrics`, and `memmap`.
- Fixes #1073.

chore: Refactor dependencies in Cargo.toml (easy)

---

src/circuit/gadgets/macros.rs
src/coprocessor/gadgets.rs
src/coroutine/memoset/demo.rs
src/coroutine/memoset/env.rs
src/coroutine/memoset/mod.rs
src/coroutine/memoset/query.rs
src/lem/store.rs

NOTE: This PR currently targets #1076 as base branch, to simplify review. The intention is that it merge after that PR, rather than be merged into it.
This PR adds `EnvQuery` and `EnvCircuitQuery` — suitable for use in Lurk to provide cheap and memoized lexical env lookups. Of note:
- The args to the query are provided as a cons, rather than a list. This enshrines the general design pattern that coroutines need not use Lurk 'calling conventions' to encode non-unary input. This helps reduce hashing costs and could be taken further.
- The result returned is a cons whose cdr is a Lurk boolean (nil or t) indicating whether the var was bound in the env, necessary for the Lurk context.
Future work:
It is worth noting that the current Lurk reduction examines 8 binding frames (`Env`s) at a time, …

Implement env lookup query.

---

Cargo.toml

- Disabled default features for Neptune package to curb unnecessary functionalities
Moves our dependency graph for blst from
```
blst v0.3.11
├── blstrs v0.7.1 (https://github.com/lurk-lab/blstrs.git?branch=dev#ea97fc1a)
│   └── neptune v13.0.0 (https://github.com/lurk-lab/neptune?branch=dev#9105c4fd)
│       ├── arecibo v0.2.0 (https://github.com/lurk-lab/arecibo?branch=dev#7a5d7bf0)
│       │   └── lurk v0.3.1 (/Users/huitseeker/tmp/lurk-rs)
│       │       [dev-dependencies]
│       │       └── lurk-macros v0.2.0 (proc-macro) (/Users/huitseeker/tmp/lurk-rs/lurk-macros)
│       │           └── lurk v0.3.1 (/Users/huitseeker/tmp/lurk-rs) (*)
│       └── lurk v0.3.1 (/Users/huitseeker/tmp/lurk-rs) (*)
│   [build-dependencies]
│   └── neptune v13.0.0 …
```

chore: Modify Neptune package features in Cargo.toml

---

examples/circom.rs
examples/sha256_ivc.rs
examples/sha256_nivc.rs
examples/tp_table.rs
src/coprocessor/sha256.rs

Addresses the examples from #1078

chore: migrate examples to the Bn256 field

---

demo/bank.lurk
demo/chained-functional-commitment.lurk
demo/functional-commitment.lurk
demo/protocol.lurk
demo/vdf.lurk
src/cli/field_data.rs
src/cli/mod.rs
src/cli/repl/meta_cmd.rs
src/cli/zstore.rs
src/field.rs
tests/lurk-cli-tests.rs

[Post #1093 and #1095]
Closes #1078

chore: make Bn256 the default field for the REPL

---

src/cli/repl/meta_cmd.rs

Update the `defprotocol` example in the REPL help command

fix defprotocol help example

---

src/lem/multiframe.rs
src/proof/nova.rs
src/proof/supernova.rs

The following profiles are from calling `lurk` with `--rc 100` and `--limit 10000` and then proving the following (infinite, but capped) computation:
```lisp
(letrec ((loop (lambda () (loop)))) (loop))
```
Before:
After:
Note: the memory peak wasn't affected on my weak machine. But if the computation is long enough (so it takes longer to generate the witnesses for all multiframes) and there is a GPU available (so each proving step is faster), used witnesses from earlier multiframes will start being cleared out before new witnesses from later frames are created.

chore: forget cached `MultiFrame` witnesses after they're used

---

Cargo.toml
lurk-macros/Cargo.toml
rust-toolchain.toml

chore: fix `udeps` and `rust-version`

---

.github/workflows/bench-pr-comment.yml

Uses the reusable workflow from https://github.com/lurk-lab/ci-workflows/pull/38. This replaces the existing `!gpu-benchmark` command with 
`!benchmark`, as shown in the following examples:
```
!benchmark
```
This will run the default benchmark settings, specified in the workflow file of this PR.
Alternatively: 
```
!benchmark --bench fibonacci --bench end2end --features cuda
LURK_RC=100,600,900
LURK_PERF="fully-sequential"
```
This will run with each of the input benchmarks, features, and env vars.
> [!IMPORTANT]
> - If you want to benchmark with GPU acceleration enabled, you *must* specify `--features cuda` in the comment body (see above example). Otherwise, the benchmarks will still run on the same GPU-equipped benchmark machine, but will run using the CPU only.
- The previous …

ci: Use configurable `!benchmark` PR comment

---

.github/workflows/nightly.yml
_typos.toml

Uses the typo checker workflow added in https://github.com/lurk-lab/ci-workflows/pull/29, which opens a PR with typo fixes and comments unsolvable typos in the PR description.
I tested the output of `typos --write-changes` locally, and fixed the false positives with the changes to `_typos.toml`. I'd welcome an alternative to the last regex which is a bit janky.

ci: Add nightly typo checker

---

Cargo.toml
src/proof/nova.rs
src/proof/supernova.rs

* Remove code duplication in Nova proving
* Factor out and reuse debugging code that was triggered only for Nova proving without "parallel steps"
* Remove the cloning of recursive snarks on SuperNova
* Drop `crossbeam` dependency because `crossbeam::thread::scope` has been soft-deprecated
in favor of `std::thread::scope` since Rust 1.63 due to performance reasons

chore: simplify and homogenize proving code for Nova and SuperNova proofs

---

src/cli/mod.rs
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs

- Solve a partial #600 in scope src/cli. 
If this PR look good, I will continue update for another scope like @arthurpaulino suggest in [this comment](https://github.com/lurk-lab/lurk-rs/pull/1106#issuecomment-1936464407)
Thank you for all review and suggestions!

Feat:recovereable error functions in scope src/cli

---

demo/protocol.lurk
src/cli/backend.rs
src/cli/lurk_proof.rs
src/cli/mod.rs
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs
src/field.rs
src/public_parameters/mod.rs

* Extend LurkProof and ProtocolProof to encode SuperNova proofs as well
* Add a new Backend::SuperNova variant
* Code the plumbing for SuperNova proof generation
* Extend the protocol API to handle a backend argument so it can use SuperNova as well
Closes #533

feat: NIVC support for the REPL

---

_typos.toml
demo/bank.lurk
demo/chained-functional-commitment.lurk
demo/functional-commitment.lurk
demo/vdf.lurk
src/cli/backend.rs
src/cli/mod.rs
src/cli/repl/meta_cmd.rs
src/field.rs
tests/lurk-cli-tests.rs

* Change Backend and LanguageField formatting so it matches the CLI formatting
* Adjust occurrences of hardcoded proof keys accordingly
Addresses @huitseeker's https://github.com/lurk-lab/lurk-rs/pull/1119#pullrequestreview-1880373514 comment

chore: default to SuperNova backend

---

src/cli/repl/meta_cmd.rs
src/lem/multiframe.rs

* Create a (new) InterpretationData to hold interpretation data on MultiFrame
* Remove some unwraps/expects because interpretation data is no longer spread across multiple holders
* [unrelated] Undo a change from #1106 where a panic was the desired behavior
cc @vuvoth

chore: unify interpretation data for MultiFrame

---

src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs

Simple change to simplify the prover trait

Frame-like M now is an associated type

---

src/coprocessor/gadgets.rs
src/coroutine/memoset/env.rs
src/coroutine/memoset/mod.rs
src/lem/store.rs
src/tag.rs

This is a follow up to #1109. It adds an explicit `Prov` tag, which is important for manipulating and observing `Provenance`s. This PR also improves general handling and printing of `Provenance`. Note that (like `Env`) there is currently no readable form for `Provenance` — and (unlike `Env`) it's unclear whether there *should* be one.
This PR is a straightforward and strict improvement — without which debugging of the `Provenance` refactor (working toward a sponge transcript) will be impossible.

Add Prov tag.

---

src/circuit/circuit_frame.rs
src/circuit/gadgets/constraints.rs
src/circuit/gadgets/data.rs
src/circuit/gadgets/macros.rs
src/circuit/gadgets/pointer.rs
src/coprocessor/gadgets.rs
src/coprocessor/mod.rs
src/coprocessor/sha256.rs
src/coprocessor/trie/mod.rs
src/coroutine/memoset/env.rs
src/coroutine/memoset/mod.rs
src/lem/circuit.rs
src/lem/multiframe.rs

- This codemod was generated by the command
```
rustby '&mut :[cs].namespace(|| :[e])' 'ns!(:[cs], :[e])'
```
where rustby is an alias for
`comby -matcher .rs -extensions .rs -in-place -jobs 10 -exclude-dir "target,.github" -stats -timeout 15 $@`
- Comprehensive refactoring done across multiple modules, including `coprocessor/mod.rs`, `coroutine/memoset/env.rs`, `circuit/circuit_frame.rs`, `circuit/gadgets/pointer.rs`, and many more.
- Switched from `.namespace()` function to the `ns!` macro throughout the code to improve simplicity and readability.

refactor: Refactor namespace allocations using `ns!` macro

---

Cargo.toml
src/coprocessor/gadgets.rs
src/coroutine/memoset/env.rs
src/coroutine/memoset/mod.rs
src/coroutine/memoset/prove.rs

This PR implement the Nova traits for coroutines. The design is kind of messy, but works. It required adding getters to Arecibo's recursive snark struct

Coroutines and Nova

---

src/coroutine/memoset/mod.rs

This PR generalizes the topological sort used when computing the provenances. The previous code relied on limitations on possible DAG shape in the singly self-recursive queries implemented so far. These changes should be fully general and support any dependency structure recorded by the queries.

Make topological sort fully general.

---

demo/chained-functional-commitment.lurk
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs

* Fix/simplify `get_comm_hash` and adjust places where it's called
* Add a variation to `demo/chained-functional-commitment.lurk` to exercise this fix
Closes #1125

fix: properly reduce commitment hash expressions on call and chain meta commands

---

src/lem/eval.rs
src/lem/macros.rs
src/lem/mod.rs

Auxiliary `Func`s don't need to be deconflicted/checked since they will eventually be checked once the main function is. This simplifies the variable names A LOT. No more stuff like `x#13#8#38#2`, but instead `x#342`
Btw, `Block` is pub now because `Func`s also are. I'm using it for the compiler of my runtime project

LEM deconflict simplification

---

src/tag.rs

This PR adds tests that enforce stability for `Tag` -> `u16` conversions.
Closes #1141 with a solution that's simpler than the manual re-implementation of conversion functions.

feat: add tests for explicit/stable tag->u16 conversion

---

Cargo.toml
src/proof/nova.rs

- Companion PR of https://github.com/lurk-lab/arecibo/pull/329
> [!NOTE]
> CI failure on initial commit due to cargo-deny expected,
> CI failure of compilation of second commit expected.

chore: Adapt to Arecibo changes (easy)

---

src/coroutine/memoset/env.rs
src/coroutine/memoset/mod.rs

Some simplifications and a fix to allocated_key

Circuit query fix

---

src/coroutine/memoset/demo.rs
src/coroutine/memoset/env.rs
src/coroutine/memoset/mod.rs
src/coroutine/memoset/query.rs

This PR refactors the `CircuitQuery` and `RecursiveCircuitQuery` traits to allow more granular implementations. This is a step toward more flexible and optimized Coroutine circuit proofs.
UPDATE: https://github.com/lurk-lab/lurk-rs/pull/1146/commits/90d76eab4182c8e07b8d5be18ccf5a4eaee1121e intends to a fix a bug whereby the allocated keys and values were not properly connected.
Notice that this fix remove a few hashes and noticeably reduces constraints, since we are now correctly reusing an allocated value rather than expensively recomputing it.

Refactor Query

---

Cargo.toml

Companion PR of
- https://github.com/lurk-lab/circom-scotia/pull/31
- https://github.com/lurk-lab/bellpepper/pull/84
> [!IMPORTANT]
> The CI failure on cargo-deny is expected (on commits pointing at the branch of the above PR).
> To stamp, please wait for the commit pointing:
> -  the bellpepper dependency back to https://github.com/lurk-rs/bellpepper@dev
> - the neptune dependency back to https://github.com/lurk-rs/neptune@dev
> - the circom-scotia dependency back to https://github.com/lurk-rs/circom-scotia@dev
> - the arecibo dependency back to https://github.com/lurk-rs/arecibo@dev

chore: depend on bellpepper-core version 0.4.0 as released

---

Cargo.toml

- Updated `pasta_curves` package to version "0.5.0" in Cargo.toml.
- Removed `pasta_curves` patch from `crates-io` due to redundancy with `bn256_grumpkin` traits.
This is obsolete since https://github.com/lurk-lab/arecibo/pull/333

chore: Update pasta_curves package and remove related patch (easy)

---

src/coroutine/memoset/demo.rs
src/coroutine/memoset/env.rs
src/coroutine/memoset/mod.rs
src/coroutine/memoset/query.rs

Some simplifications, refactors, and a generalization of `recurse` to allow any number of recursive subqueries

Coroutine simplifications and generalization

---

src/coprocessor/sha256.rs

Previously, the pallas curve had a capacity of 254 bits. The new bn256 curve has a capacity of 253 bits. This makes the pack_bits gadget used by sha256 coprocessor drop the three most significant bits of the output instead of just two.
This commit updates the coprocessor's evaluate_simple implementation to drop the three most significant bits of the hash output to avoid a potential panic caused by a mismatch between the synthesize and evaluate outputs.

Update sha256 coprocessor discarded bits

---

src/lem/eval.rs
src/lem/tests/eval_tests.rs

This PR covers a case I had forgotten in #1163: when the head of the call expression is *already* a `Comm` pointer before its evaluation.

chore: consider comm pointers as potential functions

---

lurk-macros/src/lib.rs
src/coprocessor/circom.rs
src/coprocessor/mod.rs
src/coprocessor/sha256.rs
src/coprocessor/trie/mod.rs
src/eval/lang.rs
src/lem/circuit.rs
src/lem/multiframe.rs
src/proof/tests/nova_tests.rs

* Allow coprocessor to alloc their own global constants
* Remove Coprocessor::eval_arity since the implementer already defines CoCircuit::arity
Closes #979

chore: refine Coprocessors' API

---

src/cli/repl/mod.rs
src/coprocessor/mod.rs
src/lem/eval.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs
src/proof/tests/supernova_tests.rs
src/public_parameters/instance.rs

Uncovered a weird bug where a coprocessor returning a regular value would work most times, but a list would fail as if it was trying to be interpreted. After a debugging session with @arthurpaulino, we managed to narrow down that it didn't happen with `--backend=nova` and identified the issue:
In NIVC, the Lurk circuit calls out to the coprocessor circuit (since it cannot know the value of evaluating the coprocessor in its own circuit), and then on the next fold step calls back into the main Lurk circuit with the result of the coprocessor for an extra frame. If the coprocessor returns a single value, there is no issue (since `5` evaluates to `5`), but if the coprocessor returns a list like `(1 2)`, then the lurk circuit attempts to evaluate that expression instead of simply returning it. …

Fix coprocessors returning lists in SuperNova

---

src/lem/circuit.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/multiframe.rs

This PR solves the first point in #1051. Instead of always pre-allocating output pointers we choose to do this based on whether there's a branch or not. This makes the use of auxiliary funcs cheaper. Not very important for the eval step right now, but it can be a significant improvement for small funcs, specially in the context of coroutines.

LEM circuit refactor

---

benches/end2end.rs
benches/sha256.rs
benches/synthesis.rs
src/cli/repl/mod.rs
src/coprocessor/trie/mod.rs
src/eval/lang.rs
src/lem/store.rs
src/lem/tests/eval_tests.rs
src/parser/syntax.rs
src/proof/tests/nova_tests.rs
src/state.rs
src/symbol.rs

* Discourage hardcoded parsing of symbols in favor of proper interning
* Create an alias for `Rc<RefCell<State>>` and use it across the repo
* Use `IntoIterator` in a few places
* Rewrite some functions to one-liners
* Remove closed TODOs from the top of `src/coprocessor/trie/mod.rs`

chore: several QOL improvements

---

src/circuit/gadgets/data.rs
src/coprocessor/gadgets.rs
src/lem/circuit.rs

`neptune::circuit2::poseidon_hash_allocated` already does the `is_witness_generator` check for performance so we don't need to redo this in `lurk-rs`

chore: drop `hash_poseidon` indirection

---

src/cli/zstore.rs
src/lem/store.rs

Now that we're sending Lurk data through the wire, it's important that we don't hit recursion depth limits on arbitrarily deep data.
This PR closes #1021

fix: solve deep recursion issues on some ZDag functions

---

benches/common/fib.rs
benches/end2end.rs
benches/fibonacci.rs
benches/sha256.rs
benches/synthesis.rs
examples/circom.rs
examples/sha256_ivc.rs
examples/sha256_nivc.rs
examples/tp_table.rs
src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs
src/coroutine/memoset/prove.rs
src/dual_channel.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/multiframe.rs
src/lem/tests/eval_tests.rs
src/lem/tests/misc.rs
src/lem/tests/nivc_steps.rs
src/lib.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs
src/proof/tests/supernova_tests.rs

Use `std::sync::mpsc` API to define `ChannelTerminal`, meant to work in pairs. `pair_terminals` returns a pair of such terminals such that one can send/receive messages to/from the other. Then use this to revamp LEM's `Op::Emit` so we don't need to accumulate messages on a vector internally.
This improvement also targets the future implementation of streamed proofs, which will require the CEK machine to, nondeterministically, receive data from outside.

feat: arm LEM interpretation with dual channel communitation

---

src/cli/zstore.rs
src/lem/store.rs

PR #1183 didn't include the logic for environments when collecting the children of pointers. We didn't see the error because our tests weren't checking for environment roundtrip through Z data.
Here we fix that bug and also enhance the tests to avoid future regressions.

fix: make environments roundtrip as Z data

---

src/cli/repl/meta_cmd.rs
src/cli/repl/mod.rs
src/dual_channel.rs
src/lem/interpreter.rs
src/lem/mod.rs

* Remove inner printing from the interpretation of LEM's `Op::Emit`
* Receive and handle emitted pointers in threads spawned in the REPL
* Refactor and document the REPL's evaluation functions

chore: handle emitted pointers on the REPL

---

benches/common/fib.rs
benches/end2end.rs
benches/fibonacci.rs
benches/sha256.rs
chain-server/src/server.rs
examples/keccak.rs
examples/sha256_nivc.rs
examples/tp_table.rs
src/cli/repl/mod.rs
src/coroutine/memoset/prove.rs
src/lem/circuit.rs
src/lem/coroutine/eval.rs
src/lem/coroutine/synthesis.rs
src/lem/eval.rs
src/lem/interpreter.rs
src/lem/macros.rs
src/lem/mod.rs
src/lem/multiframe.rs
src/lem/slot.rs
src/lem/store.rs
src/lem/tests/mod.rs
src/lem/tests/nivc_steps.rs
src/lem/tests/stream.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs
src/proof/tests/stream.rs
src/proof/tests/supernova_tests.rs
src/tag.rs

Introduce the `Op::Recv` LEM operator, which awaits for data to be received by the channel terminal at LEM interpretation time.
This operator is used to implement the logic for the `StreamIn` continuation, which receives the argument to be applied to the (chaining) callable object.
The result will be available once the (new) `StreamOut` continuation is reached. When that happens, the computation can be resumed by supplying two pieces of data through the channel:
* A flag to tell if the machine should stutter while in `StreamOut`
* The next argument to be consumed in the incoming `StreamIn` state
Note: the second message should not be be sent if the machine is set to stutter with the first message.
There is a test to show that we're now able to construct proofs of computations that grow …

feat: support for streamed computations and their proofs

---

Cargo.toml
benches/trie_nivc.rs
src/lem/mod.rs

Add a straightforward NIVC benchmark that uses the Trie coprocessors to create proofs with the `SuperNovaProver`.
This should be enough for a first implementation to drive design/optimization decisions for our NIVC pipeline.
Closes #1219

feat: simple NIVC benchmark with the Trie coprocessors

---

Cargo.toml
chain-server/Cargo.toml
chain-server/src/server.rs
src/cli/repl/mod.rs
src/coroutine/memoset/prove.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs

On a long enough timeline, we'll want to generate compressed proofs without dropping the associated `RecursiveProof`. This is for the purpose of re-starting the proof using the prior `RecursiveProof`, which at the moment can only be obtained through cloning prior to compression (which itself would be impossible prior to the companion PR used here).
The current approach witnesses that compression only requires a reference to the current proof, and returns a `Cow`: the only situation in which this would result in a clone is if:
- we create a `CompressedProof`,
- we call `compress()` on it,
- we further perform a modification of the resulting `CompressedProof` that requires an owned value.
=> this flow seems unlikely.
In detail:
- Updated `compress` function across various files to take …

refactor: Refactor proof handling for ownership and borrowing

---

benches/end2end.rs
benches/fibonacci.rs
benches/sha256.rs
benches/synthesis.rs
benches/trie_nivc.rs
chain-server/src/server.rs
examples/keccak.rs
examples/sha256_ivc.rs
examples/sha256_nivc.rs
examples/tp_table.rs
src/cli/lurk_proof.rs
src/cli/repl/meta_cmd.rs
src/coroutine/memoset/prove.rs
src/lem/multiframe.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs
src/proof/tests/mod.rs
src/proof/tests/nova_tests.rs
src/proof/tests/stream.rs
src/proof/tests/supernova_tests.rs
src/public_parameters/instance.rs

This removes the assumption that `prove_recursively` has access to the whole set of multiframes, by :
- removing lifetime semantics on store references, in favor of the simpler use of `Arc`,
- making `prove_recursively` operate on an `Iterator` of `MultiFrame`, opening the way for that iterator to eventually be lazy,
- making `prove_recursively`'s witness caching only run ahead of proving by at most a fixed number of frames (set to 1000),
> [!NOTE]
> This PR is split in commits matching the above bullet points, the *Commits*  view will let you inspect them separatedly.
Transferring the above memory-sparse semantics to `prove_from_frames`,`evaluate_and_prove` and other transitive consumers of `prove_recursively`. In other words, evaluation should, as much as is possible, produce an …

feat: witness caching now operates on a bounded buffer

---

src/proof/nova.rs
src/proof/supernova.rs

- Optimized the `prove_recursively` function in `RecursiveSNARKTrait` for performance enhancement
- Implemented on-demand computation for first circuit's witness in `prove_step`

refactor: witness caching skips the 1st witness.

---

chain-server/proto/chain-server.proto
chain-server/src/client.rs
chain-server/src/lib.rs
chain-server/src/server.rs
src/cli/repl/mod.rs
src/cli/zstore.rs
src/lem/eval.rs
src/lem/store.rs
src/lem/tests/stream.rs

Implements the stream mode for the chain-server, which outputs compressed proofs about the entire stream history while using previous recursive proofs as checkpoints.
Closes #1173

feat: stream mode for chain-server

---

benches/end2end.rs
benches/fibonacci.rs
benches/sha256.rs
examples/tp_table.rs
src/cli/repl/mod.rs
src/proof/mod.rs
src/proof/nova.rs
src/proof/supernova.rs

Closes #1217.
- Adds `lang()` method to the `Prover` trait
- Adds `prove_from_frames()` method to the `Prover` trait with the default implementation extracted from both `Nova` and `SuperNova`
- Adds a new `from_frames()` method to the `Prover` trait to assist the `prove_from_frames()` method
- Better name suggestions welcome here

refactor: move prove_from_frames into Prover trait

---

src/coprocessor/gadgets.rs
src/lem/coroutine/eval.rs
src/lem/store.rs

Interning/fetching environments and provenances share the same logic, so we can unify their implementations to improve code reusability.

chore: generalize compact interning and fetching

---

src/lem/interpreter.rs
src/lem/pointers.rs
src/lem/store.rs
src/lem/store_core.rs

* Factor out common code for finalizing interning
* Make `intern_digest` just return `usize`
* Improve some docstrings

chore: minor changes in `StoreCore`

---

rust-toolchain.toml
src/coprocessor/trie/mod.rs

- Updated Rust toolchain version to `1.79` for better development environment
- Simplified logic in `coprocessor/trie/mod.rs` by eliminating redundant `enumerate()` in `zip()` method use.
Companion PR of https://github.com/lurk-lab/arecibo/pull/388
Fixes #1251

chore: Update Rust toolchain
