lurk-lab/lurk-rs

- fcomm/src/lib.rs
> Cleanup dev commenting.

- .github/workflows/epics-actions.yml
This will allow creation of "epics" issues that will link to issues that serve as sub-tasks/projects within the epic. Closing issues will check one sub-task from the epic. Closing all issues will close the epic.
> Create epics-actions.yml for project management

- fcomm/examples/Makefile
> Add --lurk to Makefile where needed.

- src/circuit/gadgets/constraints.rs
Previously, `alloc_equal` would return an `AllocatedBit` (wrapped in a `Boolean`) with true value if both of its arguments had missing values (which happens during blank circuit synthesis). This was wrong. Instead the `AllocatedBit` should have value `None`. This PR fixes that and changes a few other uses of `get_value()` to use the usual idiom for error-handling — in order to make deviations which might introduce such errors more easily recognizable.
> Correctly handle missing values in alloc_equal.

- src/parser.rs
> Support underscore in symbol names.

- Cargo.toml
- README.md
As @porcuquine said in our meeting today 👍🏼
> feat: add [[bin]] section to Cargo.toml

- src/parser.rs
When treating Nums as signed, it is sometimes useful to express them with literal negated syntax. This PR adds reader support for parsing negative Nums. A Num preceded by `-` is substracted from 0 at read time.
Because the parser has only one character of lookahead, this is accomplished by adding a new parser method which optionally returns either a `Ptr` representing a `Num` or one representing a `Sym`, depending on whether or not the next character (if any) is a digit.
```
> (= -1 (- 0 1))
[6 iterations] => T
> '-asdf
[1 iterations] => -ASDF
> (< -2 -1)
[3 iterations] => T
```
> Support parsing negative Nums.

- benches/eval.rs
Cargo tests were broken for me until I added this fix.
> Fix broken cargo test

- src/eval.rs
#160 defined EVAL's optional second argument as defaulting to the current environment, but the correct default (as noted in the spec) is the empty environment. Note that the previous behavior can still be produced, if actually desired, by `(eval … (current-env))`.
> Eval optional second arg defaults to empty env.

- src/circuit/circuit_frame.rs
- src/circuit/gadgets/data.rs
- src/proof/nova.rs
- src/store.rs
This PR implements Unop and Binop for EVAL.
> Eval circuit

- src/repl.rs
> Use load path starting from pwd, not from location of lurk exe

- src/eval.rs
- src/hash_witness.rs
- src/proof/nova.rs
> Add regression test and reallocate ConsName::ClosedEnv.

- .circleci/config.yml
- README.md
- src/proof/groth16.rs
This PR is just a small refactor I came across when I was looking through the Lurk source cod and trying to figure out what was going on.
I also made the README a bit clearer on how to get started with the tests.
If you want two separate PRs, let me know.
> Small refactor

- Cargo.lock
- src/parser.rs
> Properly quote symbols.

- src/circuit/gadgets/case.rs
Some tiny touchups while reading the code.
> Small fixes in cases gadget

- fcomm/src/bin/fcomm.rs
- src/circuit/circuit_frame.rs
- src/circuit/gadgets/case.rs
- src/circuit/gadgets/constraints.rs
- src/circuit/gadgets/data.rs
- src/circuit/gadgets/pointer.rs
- src/error.rs
- src/eval.rs
- src/hash_witness.rs
- src/proof/nova.rs
- src/store.rs
- src/tag.rs
> Implement more syntax errors.

- src/circuit/circuit_frame.rs
- src/circuit/gadgets/case.rs
- src/eval.rs
#245 was auto-merged before I could address @huitseeker's comments. This PR does that.
> Minor cleanup of comments and assertions.

- src/circuit/circuit_frame.rs
- src/circuit/gadgets/pointer.rs
- src/eval.rs
- src/proof/nova.rs
> Fix binding syntax

- src/circuit/gadgets/constraints.rs
To walk in this brave new proptest world.
> Convert test_alloc_equal_const to a proptest

- .circleci/config.yml
- rust-toolchain.toml
- better cache invalidation by following the `Cargo.lock`,
- set LLVM tooling using current toolchain,
- nextest install optimizations & caching
> Rationalize some CI config

- src/circuit/circuit_frame.rs
- src/circuit/gadgets/macros.rs
- src/circuit/gadgets/pointer.rs
> Cleanups in macro usage

- fcomm/examples/Makefile
- fcomm/src/bin/fcomm.rs
- fcomm/src/lib.rs
Makefile simplification + some code warts in the CLI app.
> More fcomm improvements

- Cargo.lock
- Cargo.toml
- clutch/src/main.rs
- src/main.rs
- src/repl.rs
- src/scalar_store.rs
- tests/lurk-tests.rs
Quick and dirty adaptation of the repl to take an initial lightstore
argument
> Straw man for adding a repl option to add a ScalarStore

- spec/main.tex
> fix typo in main.tex

- src/field.rs
- src/sym.rs
> Beefs up a bit of Rustdoc

- src/scalar_store.rs
- src/store.rs
> feat: `Display` implementation for `ScalarExpression`

- clutch/Cargo.toml
- clutch/tests/clutch-smoke-test.rs
Copy the smoke test from #321 for clutch.
> Add smoke test for clutch.

- Cargo.lock
- clutch/demo/functional-commitment.lurk
- clutch/src/lib.rs
- clutch/tests/clutch-smoke-test.rs
- src/repl.rs
This PR makes it possible to 'run' files from CLI invocation in clutch -- then adds two tests running short demo scripts.
These are good tests, not only of clutch running generally but because they exercise the whole commit, prove, open, chain, verify workflow.
> Clutch Run

- clutch/demo/vdf.lurk
This PR adds a pithy demo of how to implement a minroot VDF (inefficiently) in Lurk.
> Add VDF demo.

- fcomm/src/bin/fcomm.rs
- src/circuit/gadgets/constraints.rs
- src/scalar_store.rs
- src/store.rs
Refactoring some functions on the heavier side, noticed while reading #347
> refactor: simplify a few idioms

- benches/eval.rs
- src/coprocessor.rs
- src/eval/lang.rs
- src/store.rs
Small fixes found while reviewing.
> Refactor Eval (WIP)

- src/eval/mod.rs
- src/eval/reduction.rs
> Small refactorings

- Cargo.lock
- Cargo.toml
This allows controlling for requirement of ISA extensions, along with compilation using CUDA or OpenCL.
> (Small) Expose build features more flexibly 

- README.md
Adds benchmarking instructions
> Add benchmarking instructions to the README

- src/proof/mod.rs
Closes #365 (modulo possibly making the comment more explicit about why it should terminate early now)
> Propagate errors in `outer_synthesize`

- Cargo.lock
- src/circuit/circuit_frame.rs
While having a look to think about circuit - evaluation coupling.
> Small circuit cleanups

- src/circuit/circuit_frame.rs
- src/circuit/gadgets/case.rs
> Give CaseClause a constructor 

- src/coprocessor/mod.rs
- src/eval/lang.rs
- src/proof/groth16.rs
Some light cleanup including responses to review of #393.
> Coprocessor cleanup.

- src/lem/macros.rs
Avoids a bit of code duplication
> Refactor lem macros

- CONTRIBUTING.md
- Update CONTRIBUTING.md to enhance clarity on merge criteria
- Revise workflow diagram with accurate naming
> docs: Improve pull request merge guidelines

- src/circuit/gadgets/constraints.rs
- Add a new test for enforce_implication_lc function in constraints.rs
Before I forget, this is a re-do of the sensical part of #405.
> test: Add a test for enforce_implication_lc

- benches/synthesis.rs
- src/circuit/circuit_frame.rs
- src/circuit/gadgets/constraints.rs
- src/hash.rs
- src/lem/interpreter.rs
- src/lem/mod.rs
- src/lem/symbol.rs
- src/proof/groth16.rs
- src/proof/nova.rs
This removes a few unnecessary clones - the individual commit messages are probably the best explanations.
Nothing major, just removes a few string copies in LEM.
> chore: Less cloning

- .github/workflows/pr_bench.yml
Based on https://github.com/lurk-lab/lurk-rs/actions/runs/5225520763
> Fix PR benchmark syntax error

- .github/dependabot.yml
- .github/workflows/rust.yml
- .github/workflows/upstream_update.yml
- fix update_upstream,
- add dependabot.yml for GH Actions (not yet for cargo: being cautious about signal to noise ratio until https://github.com/github/roadmap/issues/148 is fixed)
- group the GPU jobs in a single job
> Optimize ci

- src/circuit/gadgets/constraints.rs
This PR adds an alternative form of `enforce_lc_implication` that requires the provided linear combination to evaluate to zero when the premise is true. This is arguably more natural (see changed usage examples) and is an incremental step toward a minor optimization in the case that we don't want to boolean-constrain the premise. This PR, however, is independent of any such eventual usage (which may not be justifiable).
> Add enforce_lc_implication_zero.

- .github/workflows/rust.yml
- Cargo.toml
- clutch/Cargo.toml
- fcomm/Cargo.toml
- lurk-macros/Cargo.toml
Fixes #464 and simplifies updates here and in our forks
> Use workspace dependencies

- src/parser/syntax.rs
> Add test cases for #104

- Cargo.lock
- Cargo.toml
- benches/end2end.rs
- benches/fibonacci.rs
- benches/synthesis.rs
- build.rs
- clutch/src/lib.rs
- examples/fibonacci.rs
- examples/itcalc.rs
- examples/sha256.rs
- src/circuit/circuit_frame.rs
- src/circuit/gadgets/data.rs
- src/circuit/gadgets/hashes.rs
- src/config.rs
- src/eval/mod.rs
- src/hash_witness.rs
- src/lib.rs
- src/main.rs
- src/proof/groth16.rs
- src/proof/nova.rs
This is the recent work on witness generation ported to dev.
> Witness generation (ICFP benchmarks, on dev)

- clutch/src/lib.rs
- fcomm/src/bin/fcomm.rs
- fcomm/src/lib.rs
- src/circuit/circuit_frame.rs
- src/eval/tests/mod.rs
- src/parser/position.rs
- src/parser/syntax.rs
- src/proof/groth16.rs
- src/proof/nova.rs
- src/public_parameters/file_map.rs
- src/public_parameters/registry.rs
- src/store.rs
- src/syntax.rs
- src/z_data/z_store.rs
One remaining instance will be dealt with by #521
> chore: remove uneeded instances of pass-by-value

- benches/end2end.rs
- Introduced a function for Spartan prove benchmarks in `benches/end2end.rs`
- Included this new function into the benchmarking group
> feat: Implement compressed proofs benchmarking

- .github/workflows/ci.yml
- Removed the push triggers in the main CI workflow.
> ci: Refactor GitHub workflows for specific branch triggers

- src/proof/nova.rs
- Updated code comments in `src/proof/nova.rs` to clearly state that `SS1<F>` and `SS2<F>` do not utilize computational commitments
- Enhanced `public_params` function with two new parameters: `commitment_size_hint1` and `commitment_size_hint2`, aligning the setup of `nova::PublicParams` with https://github.com/lurk-lab/arecibo/pull/5
> feat: Refactor nova.rs for new Public Parameters tuned to a SNARK

- src/lem/circuit.rs
- src/lem/mod.rs
- src/proof/mod.rs
- src/proof/nova.rs
- src/proof/nova_lem.rs
- src/public_parameters/disk_cache.rs
- src/public_parameters/mem_cache.rs
- src/public_parameters/mod.rs
> refactor: Refactor proof and public parameters to account for Multiframe

- fcomm/src/file_map.rs
- fcomm/src/lib.rs
- src/circuit/circuit_frame.rs
- src/circuit/gadgets/data.rs
- src/circuit/gadgets/hashes.rs
- src/coprocessor/trie/mod.rs
- src/eval/lang.rs
- src/eval/mod.rs
- src/hash.rs
- src/lem/interpreter.rs
- src/lem/path.rs
- src/lem/pointers.rs
- src/lem/store.rs
- src/package.rs
- src/proof/groth16.rs
- src/repl.rs
- src/state.rs
- src/z_data/serde/ser.rs
- see [C-COMMON-TRAITS](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits)
> fix: derive Implement `Debug` trait across various structs and enums

- clutch/src/main.rs
remove redundant conditional check
> refactor: simplify field selection

- src/eval/lang.rs
Remove extra fields from `Lang`, as an `IndexMap`, alone, can provide the support we need.
This also makes `Lang` completely compatible with #670, which is great.
> Simplify Lang internals

- src/circuit/circuit_frame.rs
- src/proof/nova.rs
- src/proof/supernova.rs
> refactor: Tidying up changes after #677

- src/cli/repl.rs
- src/cli/repl/meta_cmd.rs
This PR also makes `Repl` hold a `pwd_path`, which avoids the need to be passing this piece of data around.
Closes #691
> Solve load bug when not in the REPL

- src/circuit/circuit_frame.rs
- src/circuit/gadgets/constraints.rs
- src/lem/circuit.rs
- src/lem/eval.rs
- src/lem/interpreter.rs
- src/lem/macros.rs
- src/lem/mod.rs
- src/lem/path.rs
- src/lem/slot.rs
- src/lem/var_map.rs
This PR adds boolean values to LEM. I've removed `IfEq` in favour of the more general `If`, which takes a boolean as argument. I've also added boolean operators `And`, `Or` and `Not`. This PR also paves the way for adding other types to LEM, such as numbers, and also makes it possible to eventually slot allocate bit decomp, since now slots can return booleans. It is still not possible to have funcs take/return booleans, and there's no static typechecking, only dynamic checks
> LEM booleans

- benches/end2end.rs
- benches/fibonacci.rs
- clutch/src/lib.rs
- examples/circom.rs
- examples/sha256.rs
- fcomm/src/lib.rs
- src/circuit/circuit_frame.rs
- src/cli/lurk_proof.rs
- src/cli/mod.rs
- src/cli/repl.rs
- src/cli/repl_lem.rs
- src/lem/interpreter.rs
- src/lem/multiframe.rs
- src/lem/store.rs
- src/proof/groth16.rs
- src/proof/mod.rs
- src/proof/nova.rs
- src/proof/nova_lem.rs
- src/public_parameters/disk_cache.rs
- src/public_parameters/mem_cache.rs
- src/public_parameters/mod.rs
For posterity, this points the way towards a `MultiFrame` trait that can be implemented by LEM & Lurk
> Lem integration Review

- examples/sha256_nivc.rs
- src/public_parameters/instance.rs
> fix: Hotfix #648 panic

- src/parser/syntax.rs
> make ';' enough to start a line comment

- .github/CODEOWNERS
- Update CODEOWNERS file to adjust circuit and eval path ownership
- no special rules for circuit and eval: co-owned @huitseeker & @porcuquine, like the rest
> chore: Refactor codeowner assignments and patterns

- src/lem/eval.rs
This PR drops some burden from our CI. It removes some tests that became obsolete after #717 and #718.
> Remove obsolete tests from `lem/eval.rs`

- src/lem/eval.rs
- src/lem/multiframe.rs
Better reuse of already existing code
> Simplify LEM's MultiFrame::get_evaluation_frames

- .github/workflows/nightly.yml
#741 repairs nightly, a workflow that was failing for ~2 months
> ci: Make the nightly job open/update issues when it fails

- src/lem/eval.rs
Some simple tweaks in the model to cut off 114 constraints
> More model adjustments to reduce the number of constraints

- src/lem/circuit.rs
- src/lem/eval.rs
- src/lem/interpreter.rs
- src/lem/mod.rs
Addresses https://github.com/lurk-lab/lurk-rs/pull/738#pullrequestreview-1681022621
> Rename 'advices' to 'hints'

- .github/workflows/nightly.yml
- Revised the nightly Github workflow's `Debug` step order and upgraded its functionality to include `status` variable output.
- Revised condition checks within the nightly Github workflow
> ci: fix nightly reporting issue

- lurk-macros/src/lib.rs
- src/circuit/circuit_frame.rs
- src/circuit/gadgets/hashes.rs
- src/coprocessor/circom.rs
- src/coprocessor/mod.rs
- src/coprocessor/sha256.rs
- src/coprocessor/trie/mod.rs
- src/eval/tests/trie.rs
- src/package.rs
- src/proof/nova.rs
- src/proof/tests/nova_tests_lurk.rs
- src/state.rs
- src/writer.rs
Closes #397.
Some issues for further work are noted in TODOs and are, I believe, captured in #745.
> Add trie coprocessor circuits.

- .github/workflows/nightly.yml
- fcomm/examples/Makefile
- fcomm/examples/chained-request.json
It works: https://asciinema.org/a/yWxditvtEtcu2Wywo47IZszEL
Closes #770
> fix: repair nightly

- benches/end2end.rs
> chore: Remove duplicate store in benches

- src/circuit/gadgets/pointer.rs
- src/coprocessor/mod.rs
This attempts to fix the circuit, as well as implementing the eval error-handling logic for alpha.
> Implement erorr-handling and circuit.

- examples/fibonacci.rs
- examples/sha256_ivc_lem.rs
Use LEM infra for fibonacci example and implement `sha256_ivc_lem.rs`
> Closing up LEM examples

- Cargo.toml
- src/proof/nova.rs
- src/proof/supernova.rs
Companion PR to https://github.com/lurk-lab/arecibo/pull/87
> Adapt to upstream Nova RecursiveSNARK API changes

- .cargo/config
- benches/common/mod.rs
- fcomm/src/lib.rs
- lurk-metrics/src/data.rs
- lurk-metrics/src/lib.rs
- lurk-metrics/src/recorder.rs
- Closes #361 and prohibits instances of [`unreachable_pub`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_lint/builtin/static.UNREACHABLE_PUB.html)
> Refactor unreachable public methods

- src/circuit/circuit_frame.rs
- src/circuit/gadgets/constraints.rs
- src/coprocessor/mod.rs
- src/lem/circuit.rs
Resolves #819 
Beginning with just calling the `add` method as defined by bellpepper over `AllocatedNum`.
> Use the new Bellpepper add gadget

- Cargo.toml
- src/proof/nova.rs
- src/proof/supernova.rs
Companion PR to https://github.com/lurk-lab/arecibo/pull/95
> fix: adapt to CK hint API changes in Arecibo

- .github/workflows/merge-tests.yml
- Enhanced the benchmark output's system information in `merge-tests.yml` to include CPU model and total RAM besides GPU name.
> ci: Enhance benchmarking traceability for bench comments

- Cargo.toml
- README.md
- fcomm/Cargo.toml
Updates dependencies & updates badges
> Maintain dependencies

- CONTRIBUTING.md
- Extended 'Lurk-rs Repository Organization and Dependency Management' section of CONTRIBUTING.md
- Outlined a comprehensive dependency management strategy for the Lurk-rs project
- Added instructions for branch management and where to apply changes
- Included a dependency diagram to visualize the project's associations with its dependencies
(this is already up-to-date with #845)
> docs: Update contributing guidelines with repository organization

- src/proof/supernova.rs
https://github.com/lurk-lab/arecibo/pull/101 will break `lurk-rs`. This PR will fix that.
> Use updated arecibo API.

- src/cli/lurk_proof.rs
Make sure that unpacked proofs are fully consistent by checking that the meta data matches the proof's public input and output.
> Protect against inconsistent meta data

- src/lem/eval.rs
- src/lem/tests/mod.rs
- src/lem/tests/nivc_steps.rs
This PR also improves NIVC steps test, making it easier to follow/understand
> Remove stuttering behavior from NIVC coprocessors

- .github/workflows/merge-tests.yml
#911 missed a few file renames. This PR should fix the merge queue GPU benchmarks
> ci: Fix #911

- benches/end2end.rs
- benches/fibonacci.rs
- benches/sha256.rs
- benches/synthesis.rs
- examples/circom.rs
- examples/sha256_ivc.rs
- examples/sha256_nivc.rs
- simplifies the review of #921
> refactor: Revert variable renamings lang / lang_rc

- demo/protocol.lurk
- src/cli/repl/meta_cmd.rs
- src/cli/repl/mod.rs
- src/lem/pointers.rs
- src/state.rs
- tests/lurk-files-tests.rs
* Add `dump-data` and `load-data` meta commands
* Add `defprotocol`, `prove-protocol` and `verify-protocol` meta commands
> Implement protocol support

- src/cli/lurk_proof.rs
- src/cli/mod.rs
- src/cli/zstore.rs
Drop pack and unpack commands, made obsolete by #942
> Kill `pack` and `unpack` commands

- .github/workflows/merge-tests.yml
> ci: Fix typo

- Cargo.toml
Companion PR of https://github.com/lurk-lab/arecibo/pull/183
> chore: update Arecibo dependency package name

- Cargo.toml
Companion PR of https://github.com/lurk-lab/arecibo/pull/192
> chore: update halo2curves dependency (easy)

- Cargo.toml
Porting the version bump commit from #986 here.
> chore: Release

- benches/fibonacci.rs
Addresses the first item of #990
> Use the `fib_frame` formula in `fibonacci_prove`

- src/cli/repl/meta_cmd.rs
- src/cli/repl/mod.rs
The load command used to use the path of the REPL, always. Now it uses the path of the file's directory if the load command was read from the file
> Fixed load command

- examples/circom.rs
- examples/sha256_ivc.rs
- tests/lurk-nivc-test.rs
> Fix examples

- Cargo.toml
- src/proof/nova.rs
This is the companion PR of https://github.com/lurk-lab/arecibo/pull/290/
> chore: adapt to arecibo changes (Easy)

- Cargo.toml
- benches/common/fib.rs
- benches/end2end.rs
- benches/fibonacci.rs
- benches/public_params.rs
- benches/sha256.rs
- benches/synthesis.rs
- src/proof/nova.rs
- src/public_parameters/instance.rs
Closes #1079 by following the instructions from https://github.com/lurk-lab/lurk-rs/pull/1039#issuecomment-1910767177
Closes #1022
Addresses benchmarks mentioned in #1078
> chore: migrate from Bn256Engine to Bn256EngineKGZ

- benches/end2end.rs
Addresses [a nit](https://github.com/lurk-lab/lurk-rs/pull/1093#discussion_r1480465659) from #1093
> Remove useless commented bench code

- src/lem/store.rs
> fix: print comm pointers correctly

- flake.lock
- flake.nix
this updates the flake so it works
> fix nix build

- demo/protocol.lurk
- src/cli/repl/meta_cmd.rs
- src/tag.rs
> fix nightly tests

- src/coprocessor/gadgets.rs
This PR just implements a tiny refactor suggested in https://github.com/lurk-lab/lurk-rs/pull/1109#discussion_r1489868363.
> Use Borrow/IntoIterator.

- src/coroutine/memoset/mod.rs
This PR removes some junk recessive genes from the MemoSet DNA — in the form of residual generality no longer applicable after intervening refactors.
> Simplify build_transcript.

- src/lem/eval.rs
- src/lem/tests/eval_tests.rs
- src/proof/tests/mod.rs
- src/proof/tests/nova_tests.rs
> feat: extend callables

- src/coroutine/memoset/demo.rs
- src/coroutine/memoset/env.rs
- src/coroutine/memoset/mod.rs
- src/coroutine/memoset/prove.rs
- src/coroutine/memoset/query.rs
This PR simplifies a bunch of methods by adding Arc<Store> to Scope and CoroutineCircuit
> Changes to Scope and CoroutineCircuit

- .github/workflows/ci.yml
Companion PR of https://github.com/lurk-lab/ci-workflows/pull/48
> chore: Adapt to `ci-workflows` changes

- .github/workflows/bench-pr-comment.yml
After https://github.com/lurk-lab/ci-workflows/pull/51
> ci: Fix `bench-pr-comment.yml`

- src/lem/circuit.rs
- src/lem/eval.rs
- src/lem/interpreter.rs
- src/lem/macros.rs
- src/lem/mod.rs
- src/lem/slot.rs
This PR introduces the more general match of values, instead of only symbols
> LEM match values

- foil/Cargo.toml
- foil/src/congruence.rs
- foil/src/constructors.rs
- src/coroutine/memoset/prove.rs
> fix: nightly errors

- src/coprocessor/gadgets.rs
- src/lem/eval.rs
- src/lem/store.rs
We already have an implementation of `car_cdr` in LEM that doesn't deal with strings in order to save constraints. We can call that `car_cdr_simple` so we know what we're talking about just by looking at it.
This diff materializes this concept in the `Store` and implements a corresponding gadget that can be used more cheaply in coprocessors. Furthemore, `chain_car_cdr` gains a `simple` flag so the caller can use it to save constraints.
> feat: formalize "car_cdr_simple"

- .github/workflows/nightly.yml
> ci: Fix `nightly.yml` deps

- benches/common/fib.rs
- chain-server/src/server.rs
- foil/src/coil.rs
- src/cli/repl/meta_cmd.rs
- src/cli/repl/mod.rs
- src/cli/zstore.rs
- src/coprocessor/gadgets.rs
- src/coroutine/memoset/demo.rs
- src/coroutine/memoset/env.rs
- src/coroutine/memoset/mod.rs
- src/lem/coroutine/eval.rs
- src/lem/coroutine/toplevel.rs
- src/lem/interpreter.rs
- src/lem/pointers.rs
- src/lem/store.rs
* avoid some copies where we already require ownership
* use `car_cdr_simple` where we're not interested in deconstructing strings
* use `fetch_cons` where we explicitly require the pointer's tag to be `Cons`
> chore: some minor improvements

- .github/workflows/merge-tests.yml
Closes https://github.com/lurk-lab/ci-workflows/issues/59
> ci: Fix M1 Mac test
